# Do not edit this file manually. It is automatically generated.
# Edit 'capture-all.sh' instead.


source ../../definitions.sh
source ../definitions.sh
source definitions.sh

_TT_check_stage_not_in_a_tps_repo


stage_dir stage
expect_exec -f "output_dir" "captured-data/k-0/probed_files/0_output_dir" -oempty -e "captured-data/k-0/stderr" run_ttis templates_dir/template1/task-template-instantiate.sh -T templates_dir -t template1 output_dir


stage_dir stage
expect_exec -f "output_dir" "captured-data/k-1/probed_files/0_output_dir" -oempty -e "captured-data/k-1/stderr" -r 11 run_replace_func template2 "prompt string myvar" py_regex_replace_in_files -- -D myvar=REPL

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-2/probed_files/0_output_dir" -oempty -e "captured-data/k-2/stderr" -r 11 run_replace_func template2 "prompt string myvar" "py_regex_replace_in_files \"str1\"" -- -D myvar=REPL

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-3/probed_files/0_output_dir" -oempty -e "captured-data/k-3/stderr" -r 14 run_replace_func template2 "prompt string myvar" "py_regex_replace_in_files \"str1\" \"\${myvar}\" \"non-exist\"" -- -D myvar=REPL

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-4/probed_files/0_output_dir" -oempty -e "captured-data/k-4/stderr" -r 14 run_replace_func template2 "prompt string myvar" "py_regex_replace_in_files \"str1\" \"\${myvar}\" \"a_dir\"" -- -D myvar=REPL


stage_dir stage
expect_exec -f "output_dir" "captured-data/k-5/probed_files/0_output_dir" -oempty -e "captured-data/k-5/stderr" run_replace_func template2 "prompt string myvar" "py_regex_replace_in_files \"str1\" \"\${myvar}\"" -- -D myvar=REPL

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-6/probed_files/0_output_dir" -oempty -e "captured-data/k-6/stderr" run_replace_func template2 "prompt string myvar" "py_regex_replace_in_files \"str1\" \"\${myvar}\" \"boo.sh\"" -- -D myvar=REPL

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-7/probed_files/0_output_dir" -oempty -e "captured-data/k-7/stderr" run_replace_func template2 "prompt string myvar" "py_regex_replace_in_files \"str1\" \"\${myvar}\" \".foo.sh\"" -- -D myvar=REPL

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-8/probed_files/0_output_dir" -oempty -e "captured-data/k-8/stderr" run_replace_func template2 "prompt string myvar" "py_regex_replace_in_files \"str1\" \"\${myvar}\" \"boo.sh\" \".foo.sh\"" -- -D myvar=REPL

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-9/probed_files/0_output_dir" -oempty -e "captured-data/k-9/stderr" run_replace_func template2 "prompt string myvar" "py_regex_replace_in_files \"str1\" \"\${myvar}\" \"a_dir/boo.sh\"" -- -D myvar=REPL


stage_dir stage
expect_exec -fu "output_dir" -f "templates_dir/template3/dir1" "captured-data/k-10/probed_files/1_templates_dir_dir1" -oempty -e "captured-data/k-10/stderr" -r 12 run_replace_func template3 "" "py_regex_replace_in_files \"str\" \"rep\" \"dir1/a_str.txt\""
