# Do not edit this file manually. It is automatically generated.
# Edit 'capture-all.sh' instead.


source ../../definitions.sh
source ../definitions.sh
source definitions.sh

_TT_check_stage_not_in_a_tps_repo


stage_dir stage
expect_exec -f "a_new_dir" "captured-data/k-0/probed_files/0_a_new_dir" -f "templates_dir/default" "captured-data/k-0/probed_files/1_templates_dir_default" -ih 1 -oempty -e "captured-data/k-0/stderr" run_clone default a_new_dir with_prompt

stage_dir stage
expect_exec -f "a_new_dir" "captured-data/k-1/probed_files/0_a_new_dir" -f "templates_dir/default" "captured-data/k-1/probed_files/1_templates_dir_default" -oempty -e "captured-data/k-1/stderr" run_clone default a_new_dir with_prompt -- --define a_variable=5

stage_dir stage
expect_exec -f "another_new_dir" "captured-data/k-2/probed_files/0_another_new_dir" -f "templates_dir/default" "captured-data/k-2/probed_files/1_templates_dir_default" -oempty -e "captured-data/k-2/stderr" run_clone default another_new_dir

stage_dir stage
expect_exec -f "a_new_dir" "captured-data/k-3/probed_files/0_a_new_dir" -f "templates_dir/empty" "captured-data/k-3/probed_files/1_templates_dir_empty" -ih 1 -oempty -e "captured-data/k-3/stderr" run_clone empty a_new_dir with_prompt

stage_dir stage
expect_exec -f "a_new_dir" "captured-data/k-4/probed_files/0_a_new_dir" -f "templates_dir/empty" "captured-data/k-4/probed_files/1_templates_dir_empty" -oempty -e "captured-data/k-4/stderr" run_clone empty a_new_dir with_prompt -- --define a_variable=5

stage_dir stage
expect_exec -f "another_new_dir" "captured-data/k-5/probed_files/0_another_new_dir" -f "templates_dir/empty" "captured-data/k-5/probed_files/1_templates_dir_empty" -oempty -e "captured-data/k-5/stderr" run_clone empty another_new_dir

stage_dir stage
expect_exec -f "a_new_dir" "captured-data/k-6/probed_files/0_a_new_dir" -f "templates_dir/single" "captured-data/k-6/probed_files/1_templates_dir_single" -ih 1 -oempty -e "captured-data/k-6/stderr" run_clone single a_new_dir with_prompt

stage_dir stage
expect_exec -f "a_new_dir" "captured-data/k-7/probed_files/0_a_new_dir" -f "templates_dir/single" "captured-data/k-7/probed_files/1_templates_dir_single" -oempty -e "captured-data/k-7/stderr" run_clone single a_new_dir with_prompt -- --define a_variable=5

stage_dir stage
expect_exec -f "another_new_dir" "captured-data/k-8/probed_files/0_another_new_dir" -f "templates_dir/single" "captured-data/k-8/probed_files/1_templates_dir_single" -oempty -e "captured-data/k-8/stderr" run_clone single another_new_dir
