# Do not edit this file manually. It is automatically generated.
# Edit 'capture-all.sh' instead.

source ../definition_source_util_sh.sh

stage_an_empty_dir

expect_exec -oempty -eempty is_identifier_format t
expect_exec -oempty -eempty is_identifier_format hi
expect_exec -oempty -eempty -r 1 is_identifier_format "hey you"
expect_exec -oempty -eempty is_identifier_format hey_you
expect_exec -oempty -eempty is_identifier_format hi3
expect_exec -oempty -eempty -r 1 is_identifier_format 3hi
expect_exec -oempty -eempty is_identifier_format h3i
expect_exec -oempty -eempty is_identifier_format aa
expect_exec -oempty -eempty -r 1 is_identifier_format 1a
expect_exec -oempty -eempty -r 1 is_identifier_format 1
expect_exec -oempty -eempty is_identifier_format _
expect_exec -oempty -eempty is_identifier_format _a
expect_exec -oempty -eempty is_identifier_format _1
expect_exec -oempty -eempty is_identifier_format a_
expect_exec -oempty -eempty -r 1 is_identifier_format 1_

expect_exec -oempty -eempty is_unsigned_integer_format 0
expect_exec -oempty -eempty is_unsigned_integer_format 3
expect_exec -oempty -eempty is_unsigned_integer_format 13
expect_exec -oempty -eempty -r 1 is_unsigned_integer_format 0.0
expect_exec -oempty -eempty -r 1 is_unsigned_integer_format 1.2
expect_exec -oempty -eempty -r 1 is_unsigned_integer_format 1.
expect_exec -oempty -eempty -r 1 is_unsigned_integer_format .2
expect_exec -oempty -eempty -r 1 is_unsigned_integer_format ""
expect_exec -oempty -eempty -r 1 is_unsigned_integer_format " "
expect_exec -oempty -eempty -r 1 is_unsigned_integer_format .
expect_exec -oempty -eempty -r 1 is_unsigned_integer_format x
expect_exec -oempty -eempty -r 1 is_unsigned_integer_format 2x
expect_exec -oempty -eempty -r 1 is_unsigned_integer_format x2
expect_exec -oempty -eempty -r 1 is_unsigned_integer_format 1.x
expect_exec -oempty -eempty -r 1 is_unsigned_integer_format .x
expect_exec -oempty -eempty -r 1 is_unsigned_integer_format x.2
expect_exec -oempty -eempty -r 1 is_unsigned_integer_format x.
expect_exec -oempty -eempty -r 1 is_unsigned_integer_format +0
expect_exec -oempty -eempty -r 1 is_unsigned_integer_format +3
expect_exec -oempty -eempty -r 1 is_unsigned_integer_format +13
expect_exec -oempty -eempty -r 1 is_unsigned_integer_format +0.0
expect_exec -oempty -eempty -r 1 is_unsigned_integer_format +1.2
expect_exec -oempty -eempty -r 1 is_unsigned_integer_format +1.
expect_exec -oempty -eempty -r 1 is_unsigned_integer_format +.2
expect_exec -oempty -eempty -r 1 is_unsigned_integer_format +
expect_exec -oempty -eempty -r 1 is_unsigned_integer_format "+ "
expect_exec -oempty -eempty -r 1 is_unsigned_integer_format +.
expect_exec -oempty -eempty -r 1 is_unsigned_integer_format +x
expect_exec -oempty -eempty -r 1 is_unsigned_integer_format +2x
expect_exec -oempty -eempty -r 1 is_unsigned_integer_format +x2
expect_exec -oempty -eempty -r 1 is_unsigned_integer_format +1.x
expect_exec -oempty -eempty -r 1 is_unsigned_integer_format +.x
expect_exec -oempty -eempty -r 1 is_unsigned_integer_format +x.2
expect_exec -oempty -eempty -r 1 is_unsigned_integer_format +x.
expect_exec -oempty -eempty -r 1 is_unsigned_integer_format -0
expect_exec -oempty -eempty -r 1 is_unsigned_integer_format -3
expect_exec -oempty -eempty -r 1 is_unsigned_integer_format -13
expect_exec -oempty -eempty -r 1 is_unsigned_integer_format -0.0
expect_exec -oempty -eempty -r 1 is_unsigned_integer_format -1.2
expect_exec -oempty -eempty -r 1 is_unsigned_integer_format -1.
expect_exec -oempty -eempty -r 1 is_unsigned_integer_format -.2
expect_exec -oempty -eempty -r 1 is_unsigned_integer_format -
expect_exec -oempty -eempty -r 1 is_unsigned_integer_format "- "
expect_exec -oempty -eempty -r 1 is_unsigned_integer_format -.
expect_exec -oempty -eempty -r 1 is_unsigned_integer_format -x
expect_exec -oempty -eempty -r 1 is_unsigned_integer_format -2x
expect_exec -oempty -eempty -r 1 is_unsigned_integer_format -x2
expect_exec -oempty -eempty -r 1 is_unsigned_integer_format -1.x
expect_exec -oempty -eempty -r 1 is_unsigned_integer_format -.x
expect_exec -oempty -eempty -r 1 is_unsigned_integer_format -x.2
expect_exec -oempty -eempty -r 1 is_unsigned_integer_format -x.

expect_exec -oempty -eempty is_signed_integer_format 0
expect_exec -oempty -eempty is_signed_integer_format 3
expect_exec -oempty -eempty is_signed_integer_format 13
expect_exec -oempty -eempty -r 1 is_signed_integer_format 0.0
expect_exec -oempty -eempty -r 1 is_signed_integer_format 1.2
expect_exec -oempty -eempty -r 1 is_signed_integer_format 1.
expect_exec -oempty -eempty -r 1 is_signed_integer_format .2
expect_exec -oempty -eempty -r 1 is_signed_integer_format ""
expect_exec -oempty -eempty -r 1 is_signed_integer_format " "
expect_exec -oempty -eempty -r 1 is_signed_integer_format .
expect_exec -oempty -eempty -r 1 is_signed_integer_format x
expect_exec -oempty -eempty -r 1 is_signed_integer_format 2x
expect_exec -oempty -eempty -r 1 is_signed_integer_format x2
expect_exec -oempty -eempty -r 1 is_signed_integer_format 1.x
expect_exec -oempty -eempty -r 1 is_signed_integer_format .x
expect_exec -oempty -eempty -r 1 is_signed_integer_format x.2
expect_exec -oempty -eempty -r 1 is_signed_integer_format x.
expect_exec -oempty -eempty is_signed_integer_format +0
expect_exec -oempty -eempty is_signed_integer_format +3
expect_exec -oempty -eempty is_signed_integer_format +13
expect_exec -oempty -eempty -r 1 is_signed_integer_format +0.0
expect_exec -oempty -eempty -r 1 is_signed_integer_format +1.2
expect_exec -oempty -eempty -r 1 is_signed_integer_format +1.
expect_exec -oempty -eempty -r 1 is_signed_integer_format +.2
expect_exec -oempty -eempty -r 1 is_signed_integer_format +
expect_exec -oempty -eempty -r 1 is_signed_integer_format "+ "
expect_exec -oempty -eempty -r 1 is_signed_integer_format +.
expect_exec -oempty -eempty -r 1 is_signed_integer_format +x
expect_exec -oempty -eempty -r 1 is_signed_integer_format +2x
expect_exec -oempty -eempty -r 1 is_signed_integer_format +x2
expect_exec -oempty -eempty -r 1 is_signed_integer_format +1.x
expect_exec -oempty -eempty -r 1 is_signed_integer_format +.x
expect_exec -oempty -eempty -r 1 is_signed_integer_format +x.2
expect_exec -oempty -eempty -r 1 is_signed_integer_format +x.
expect_exec -oempty -eempty is_signed_integer_format -0
expect_exec -oempty -eempty is_signed_integer_format -3
expect_exec -oempty -eempty is_signed_integer_format -13
expect_exec -oempty -eempty -r 1 is_signed_integer_format -0.0
expect_exec -oempty -eempty -r 1 is_signed_integer_format -1.2
expect_exec -oempty -eempty -r 1 is_signed_integer_format -1.
expect_exec -oempty -eempty -r 1 is_signed_integer_format -.2
expect_exec -oempty -eempty -r 1 is_signed_integer_format -
expect_exec -oempty -eempty -r 1 is_signed_integer_format "- "
expect_exec -oempty -eempty -r 1 is_signed_integer_format -.
expect_exec -oempty -eempty -r 1 is_signed_integer_format -x
expect_exec -oempty -eempty -r 1 is_signed_integer_format -2x
expect_exec -oempty -eempty -r 1 is_signed_integer_format -x2
expect_exec -oempty -eempty -r 1 is_signed_integer_format -1.x
expect_exec -oempty -eempty -r 1 is_signed_integer_format -.x
expect_exec -oempty -eempty -r 1 is_signed_integer_format -x.2
expect_exec -oempty -eempty -r 1 is_signed_integer_format -x.

expect_exec -oempty -eempty is_unsigned_decimal_format 0
expect_exec -oempty -eempty is_unsigned_decimal_format 3
expect_exec -oempty -eempty is_unsigned_decimal_format 13
expect_exec -oempty -eempty is_unsigned_decimal_format 0.0
expect_exec -oempty -eempty is_unsigned_decimal_format 1.2
expect_exec -oempty -eempty is_unsigned_decimal_format 1.
expect_exec -oempty -eempty is_unsigned_decimal_format .2
expect_exec -oempty -eempty -r 1 is_unsigned_decimal_format ""
expect_exec -oempty -eempty -r 1 is_unsigned_decimal_format " "
expect_exec -oempty -eempty -r 1 is_unsigned_decimal_format .
expect_exec -oempty -eempty -r 1 is_unsigned_decimal_format x
expect_exec -oempty -eempty -r 1 is_unsigned_decimal_format 2x
expect_exec -oempty -eempty -r 1 is_unsigned_decimal_format x2
expect_exec -oempty -eempty -r 1 is_unsigned_decimal_format 1.x
expect_exec -oempty -eempty -r 1 is_unsigned_decimal_format .x
expect_exec -oempty -eempty -r 1 is_unsigned_decimal_format x.2
expect_exec -oempty -eempty -r 1 is_unsigned_decimal_format x.
expect_exec -oempty -eempty -r 1 is_unsigned_decimal_format +0
expect_exec -oempty -eempty -r 1 is_unsigned_decimal_format +3
expect_exec -oempty -eempty -r 1 is_unsigned_decimal_format +13
expect_exec -oempty -eempty -r 1 is_unsigned_decimal_format +0.0
expect_exec -oempty -eempty -r 1 is_unsigned_decimal_format +1.2
expect_exec -oempty -eempty -r 1 is_unsigned_decimal_format +1.
expect_exec -oempty -eempty -r 1 is_unsigned_decimal_format +.2
expect_exec -oempty -eempty -r 1 is_unsigned_decimal_format +
expect_exec -oempty -eempty -r 1 is_unsigned_decimal_format "+ "
expect_exec -oempty -eempty -r 1 is_unsigned_decimal_format +.
expect_exec -oempty -eempty -r 1 is_unsigned_decimal_format +x
expect_exec -oempty -eempty -r 1 is_unsigned_decimal_format +2x
expect_exec -oempty -eempty -r 1 is_unsigned_decimal_format +x2
expect_exec -oempty -eempty -r 1 is_unsigned_decimal_format +1.x
expect_exec -oempty -eempty -r 1 is_unsigned_decimal_format +.x
expect_exec -oempty -eempty -r 1 is_unsigned_decimal_format +x.2
expect_exec -oempty -eempty -r 1 is_unsigned_decimal_format +x.
expect_exec -oempty -eempty -r 1 is_unsigned_decimal_format -0
expect_exec -oempty -eempty -r 1 is_unsigned_decimal_format -3
expect_exec -oempty -eempty -r 1 is_unsigned_decimal_format -13
expect_exec -oempty -eempty -r 1 is_unsigned_decimal_format -0.0
expect_exec -oempty -eempty -r 1 is_unsigned_decimal_format -1.2
expect_exec -oempty -eempty -r 1 is_unsigned_decimal_format -1.
expect_exec -oempty -eempty -r 1 is_unsigned_decimal_format -.2
expect_exec -oempty -eempty -r 1 is_unsigned_decimal_format -
expect_exec -oempty -eempty -r 1 is_unsigned_decimal_format "- "
expect_exec -oempty -eempty -r 1 is_unsigned_decimal_format -.
expect_exec -oempty -eempty -r 1 is_unsigned_decimal_format -x
expect_exec -oempty -eempty -r 1 is_unsigned_decimal_format -2x
expect_exec -oempty -eempty -r 1 is_unsigned_decimal_format -x2
expect_exec -oempty -eempty -r 1 is_unsigned_decimal_format -1.x
expect_exec -oempty -eempty -r 1 is_unsigned_decimal_format -.x
expect_exec -oempty -eempty -r 1 is_unsigned_decimal_format -x.2
expect_exec -oempty -eempty -r 1 is_unsigned_decimal_format -x.

expect_exec -oempty -eempty is_signed_decimal_format 0
expect_exec -oempty -eempty is_signed_decimal_format 3
expect_exec -oempty -eempty is_signed_decimal_format 13
expect_exec -oempty -eempty is_signed_decimal_format 0.0
expect_exec -oempty -eempty is_signed_decimal_format 1.2
expect_exec -oempty -eempty is_signed_decimal_format 1.
expect_exec -oempty -eempty is_signed_decimal_format .2
expect_exec -oempty -eempty -r 1 is_signed_decimal_format ""
expect_exec -oempty -eempty -r 1 is_signed_decimal_format " "
expect_exec -oempty -eempty -r 1 is_signed_decimal_format .
expect_exec -oempty -eempty -r 1 is_signed_decimal_format x
expect_exec -oempty -eempty -r 1 is_signed_decimal_format 2x
expect_exec -oempty -eempty -r 1 is_signed_decimal_format x2
expect_exec -oempty -eempty -r 1 is_signed_decimal_format 1.x
expect_exec -oempty -eempty -r 1 is_signed_decimal_format .x
expect_exec -oempty -eempty -r 1 is_signed_decimal_format x.2
expect_exec -oempty -eempty -r 1 is_signed_decimal_format x.
expect_exec -oempty -eempty is_signed_decimal_format +0
expect_exec -oempty -eempty is_signed_decimal_format +3
expect_exec -oempty -eempty is_signed_decimal_format +13
expect_exec -oempty -eempty is_signed_decimal_format +0.0
expect_exec -oempty -eempty is_signed_decimal_format +1.2
expect_exec -oempty -eempty is_signed_decimal_format +1.
expect_exec -oempty -eempty is_signed_decimal_format +.2
expect_exec -oempty -eempty -r 1 is_signed_decimal_format +
expect_exec -oempty -eempty -r 1 is_signed_decimal_format "+ "
expect_exec -oempty -eempty -r 1 is_signed_decimal_format +.
expect_exec -oempty -eempty -r 1 is_signed_decimal_format +x
expect_exec -oempty -eempty -r 1 is_signed_decimal_format +2x
expect_exec -oempty -eempty -r 1 is_signed_decimal_format +x2
expect_exec -oempty -eempty -r 1 is_signed_decimal_format +1.x
expect_exec -oempty -eempty -r 1 is_signed_decimal_format +.x
expect_exec -oempty -eempty -r 1 is_signed_decimal_format +x.2
expect_exec -oempty -eempty -r 1 is_signed_decimal_format +x.
expect_exec -oempty -eempty is_signed_decimal_format -0
expect_exec -oempty -eempty is_signed_decimal_format -3
expect_exec -oempty -eempty is_signed_decimal_format -13
expect_exec -oempty -eempty is_signed_decimal_format -0.0
expect_exec -oempty -eempty is_signed_decimal_format -1.2
expect_exec -oempty -eempty is_signed_decimal_format -1.
expect_exec -oempty -eempty is_signed_decimal_format -.2
expect_exec -oempty -eempty -r 1 is_signed_decimal_format -
expect_exec -oempty -eempty -r 1 is_signed_decimal_format "- "
expect_exec -oempty -eempty -r 1 is_signed_decimal_format -.
expect_exec -oempty -eempty -r 1 is_signed_decimal_format -x
expect_exec -oempty -eempty -r 1 is_signed_decimal_format -2x
expect_exec -oempty -eempty -r 1 is_signed_decimal_format -x2
expect_exec -oempty -eempty -r 1 is_signed_decimal_format -1.x
expect_exec -oempty -eempty -r 1 is_signed_decimal_format -.x
expect_exec -oempty -eempty -r 1 is_signed_decimal_format -x.2
expect_exec -oempty -eempty -r 1 is_signed_decimal_format -x.

