# Do not edit this file manually. It is automatically generated.
# Edit 'capture-all.sh' instead.

source ../../definition_get_head.sh
source ../../definition_not_web_terminal.sh
source definitions.sh


stage_dir_with_scripts stage-without-checker

expect_exec -oempty -e "captured-data/k-0/stderr" tinvoke --help
expect_exec -oempty -e "captured-data/k-1/stderr" -rnz tinvoke
expect_exec -oempty -e "captured-data/k-2/stderr" -rnz tinvoke solution/correct1.cpp another-arg
expect_exec -oempty -e "captured-data/k-3/stderr" -rnz tinvoke solution/correct1.cpp --unknown-flag
expect_exec -oempty -e "captured-data/k-4/stderr" -rnz tinvoke solution/correct1.cpp --time-limit=x
expect_exec -oempty -e "captured-data/k-5/stderr" -rnz tinvoke solution/correct1.cpp --time-limit=-2
expect_exec -oempty -e "captured-data/k-6/stderr" -rnz tinvoke solution/correct1.cpp --hard-time-limit=x
expect_exec -oempty -e "captured-data/k-7/stderr" -rnz tinvoke solution/correct1.cpp --hard-time-limit=-2
expect_exec -oempty -e "captured-data/k-8/stderr" -rnz tinvoke solution/correct1.cpp --time-limit=2 --hard-time-limit=1
expect_exec -oempty -eh2 "Solution file 'nonexist.cpp' not found." "Given address: 'solution/nonexist.cpp'" -rnz tinvoke solution/nonexist.cpp

expect_exec -oempty -eh2 "Tests directory 'new-test-dir' not found." "Given address: 'new-test-dir'" -rnz tinvoke --tests-dir=new-test-dir solution/correct1.cpp
run_in_stage mkdir new-test-dir
expect_exec -oh3 "solution            compile[OK]" "" "Terminated." -eh2 "Error:" "Tests are not correctly generated." -rnz get_head 3 2 tinvoke --tests-dir=new-test-dir solution/correct1.cpp

expect_exec -o "captured-data/k-12/stdout" -eempty tinvoke solution/correct1.cpp
expect_exec -o "captured-data/k-13/stdout" -eempty tinvoke solution/wrong1.cpp
expect_exec -o "captured-data/k-14/stdout" -eempty tinvoke solution/rte1.cpp
expect_exec -o "captured-data/k-15/stdout" -eempty tinvoke solution/slow1.cpp
expect_exec -o "captured-data/k-16/stdout" -eempty tinvoke solution/slow2.cpp
expect_exec -o "captured-data/k-17/stdout" -eempty tinvoke solution/correct1.py
expect_exec -o "captured-data/k-18/stdout" -eempty tinvoke solution/wrong1.py
expect_exec -o "captured-data/k-19/stdout" -eempty tinvoke solution/rte1.py
expect_exec -o "captured-data/k-20/stdout" -eempty tinvoke solution/slow1.py

expect_exec -o "captured-data/k-21/stdout" -eempty tinvoke -r solution/correct1.cpp
expect_exec -o "captured-data/k-22/stdout" -eempty tinvoke -r solution/wrong1.cpp
expect_exec -o "captured-data/k-23/stdout" -eempty tinvoke -r solution/rte1.cpp
expect_exec -o "captured-data/k-24/stdout" -eempty tinvoke -r solution/slow1.cpp
expect_exec -o "captured-data/k-25/stdout" -eempty tinvoke -r solution/slow2.cpp

expect_exec -oh "solution            compile[FAIL]" -eempty -rnz get_head 1 1 tinvoke solution/compile_error.cpp

expect_exec -o "captured-data/k-27/stdout" -eempty tinvoke solution/correct1-warn.cpp
expect_exec -o "captured-data/k-28/stdout" -eempty tinvoke --no-sol-compile solution/correct1-warn.cpp
expect_exec -o "captured-data/k-29/stdout" -eempty tinvoke -s solution/correct1-warn.cpp
expect_exec -oh3 "solution            compile[WARN]" "exit-code: 0" "warnings:" -eempty -rnz get_head 3 3 tinvoke -w solution/correct1-warn.cpp

expect_exec -o "captured-data/k-31/stdout" -eempty tinvoke --no-check solution/correct1.cpp
expect_exec -o "captured-data/k-32/stdout" -eempty tinvoke --no-check solution/rte1.cpp
expect_exec -o "captured-data/k-33/stdout" -eempty tinvoke --no-check solution/slow1.cpp

expect_exec -o "captured-data/k-34/stdout" -eempty tinvoke -r --no-check solution/correct1.cpp
expect_exec -o "captured-data/k-35/stdout" -eempty tinvoke -r --no-check solution/rte1.cpp
expect_exec -o "captured-data/k-36/stdout" -eempty tinvoke -r --no-check solution/slow1.cpp

expect_exec -o "captured-data/k-37/stdout" -eempty tinvoke solution/slow2.cpp -r --no-tle
expect_exec -o "captured-data/k-38/stdout" -eempty tinvoke solution/slow2.cpp -r --time-limit=3.5
expect_exec -o "captured-data/k-39/stdout" -eempty tinvoke solution/slow1.cpp -r --time-limit=3.5
expect_exec -o "captured-data/k-40/stdout" -eempty tinvoke solution/slow1.cpp -r --hard-time-limit=4.5

run_in_stage rm -f tests/0-01.in
expect_exec -o "captured-data/k-41/stdout" -eh2 "Missing tests: 0-01" "Missing 1 test!" tinvoke -r solution/correct1.cpp
expect_exec -o "captured-data/k-42/stdout" -eh2 "Missing tests: 0-01" "Missing 1 test!" tinvoke -r -s solution/correct1.cpp
run_in_stage rm -f tests/1-01.out
expect_exec -o "captured-data/k-43/stdout" -eh2 "Missing tests: 0-01, 1-01" "Missing 2 tests!" tinvoke -r solution/correct1.cpp
expect_exec -o "captured-data/k-44/stdout" -eh2 "Missing tests: 0-01, 1-01" "Missing 2 tests!" tinvoke -r -s solution/correct1.cpp


stage_dir_with_scripts stage-with-checker

expect_exec -o "captured-data/k-45/stdout" -eempty tinvoke solution/correct1.cpp
expect_exec -o "captured-data/k-46/stdout" -eempty tinvoke solution/wrong1.cpp
expect_exec -o "captured-data/k-47/stdout" -eempty tinvoke solution/rte1.cpp
expect_exec -o "captured-data/k-48/stdout" -eempty tinvoke solution/slow1.cpp

expect_exec -o "captured-data/k-49/stdout" -eempty tinvoke -r solution/correct1.cpp
expect_exec -o "captured-data/k-50/stdout" -eempty tinvoke -r solution/wrong1.cpp
expect_exec -o "captured-data/k-51/stdout" -eempty tinvoke -r solution/rte1.cpp
expect_exec -o "captured-data/k-52/stdout" -eempty tinvoke -r solution/slow1.cpp
expect_exec -o "captured-data/k-53/stdout" -eempty tinvoke -r solution/slow2.cpp

expect_exec -o "captured-data/k-54/stdout" -eempty tinvoke --no-check solution/correct1.cpp
expect_exec -o "captured-data/k-55/stdout" -eempty tinvoke --no-check solution/rte1.cpp
expect_exec -o "captured-data/k-56/stdout" -eempty tinvoke --no-check solution/slow1.cpp

expect_exec -o "captured-data/k-57/stdout" -eempty tinvoke -r --no-check solution/correct1.cpp
expect_exec -o "captured-data/k-58/stdout" -eempty tinvoke -r --no-check solution/rte1.cpp
expect_exec -o "captured-data/k-59/stdout" -eempty tinvoke -r --no-check solution/slow1.cpp


stage_dir_with_scripts stage-with-checker


run_in_stage rm -f checker/checker.cpp
expect_exec -o "captured-data/k-60/stdout" -eempty tinvoke solution/correct1.cpp
expect_exec -o "captured-data/k-61/stdout" -eempty tinvoke solution/correct1.cpp -r
expect_exec -o "captured-data/k-62/stdout" -eempty -rnz get_head 5 5 tinvoke solution/correct1.cpp -s
expect_exec -o "captured-data/k-63/stdout" -eempty -rnz get_head 5 5 tinvoke solution/correct1.cpp -sr

run_in_stage cp extra/checker-ce.cpp checker/checker.cpp
expect_exec -oh3 "solution            compile[OK]" "checker             compile[FAIL]" "exit-code: 2" -eempty -rnz get_head 3 3 tinvoke solution/correct1.cpp

run_in_stage cp extra/checker-warn.cpp checker/checker.cpp
expect_exec -o "captured-data/k-65/stdout" -eempty tinvoke solution/correct1.cpp
expect_exec -oh4 "solution            compile[OK]" "checker             compile[WARN]" "exit-code: 0" "warnings:" -eempty -rnz get_head 4 4 tinvoke solution/correct1.cpp -w

run_in_stage cp extra/checker-rte.cpp checker/checker.cpp
expect_exec -o "captured-data/k-67/stdout" -eempty tinvoke solution/correct1.cpp
expect_exec -o "captured-data/k-68/stdout" -eempty tinvoke solution/correct1.cpp -r
expect_exec -o "captured-data/k-69/stdout" -eempty -rnz get_head 7 7 tinvoke solution/correct1.cpp -s
expect_exec -o "captured-data/k-70/stdout" -eempty -rnz get_head 7 7 tinvoke solution/correct1.cpp -sr

run_in_stage cp extra/checker-fail.cpp checker/checker.cpp
expect_exec -o "captured-data/k-71/stdout" -eempty tinvoke solution/correct1.cpp
expect_exec -o "captured-data/k-72/stdout" -eempty tinvoke solution/correct1.cpp -r
expect_exec -o "captured-data/k-73/stdout" -eempty tinvoke solution/correct1.cpp -s
expect_exec -o "captured-data/k-74/stdout" -eempty tinvoke solution/correct1.cpp -sr

run_in_stage rm -rf checker
expect_exec -oh2 "solution            compile[OK]" "checker             compile[FAIL]" -eempty -rnz get_head 2 2 tinvoke solution/correct1.cpp
