# Do not edit this file manually. It is automatically generated.
# Edit 'capture-all.sh' instead.


source ../../definitions.sh
source ../definitions.sh
source definitions.sh

_TT_check_stage_not_in_a_tps_repo

stage_dir stage
expect_exec -oempty -e "captured-data/k-0/stderr" -r 11 run_plain_gen generate_random_string

stage_dir stage
expect_exec -oempty -e "captured-data/k-1/stderr" -r 11 run_plain_gen "generate_random_string \"1\""

stage_dir stage
expect_exec -oempty -e "captured-data/k-2/stderr" -r 11 run_plain_gen "generate_random_string \"1\" \"a\" \"s\" \"extra\""

stage_dir stage
expect_exec -oempty -e "captured-data/k-3/stderr" -r 11 run_plain_gen "generate_random_string \"x\" \"a\" \"s\""

stage_dir stage
expect_exec -oempty -e "captured-data/k-4/stderr" -r 11 run_plain_gen "generate_random_string \"-1\" \"a\" \"s\""


stage_dir stage
expect_exec -oh "" -eempty run_plain_gen "generate_random_string \"0\" \"a\" \"s\""

stage_dir stage
expect_exec -oh "a" -eempty run_plain_gen "generate_random_string \"1\" \"a\" \"s\""

stage_dir stage
expect_exec -oh "aa" -eempty run_plain_gen "generate_random_string \"2\" \"a\" \"s\""


stage_dir stage
expect_exec -o "captured-data/k-8/stdout" -eempty run_ttis templates_dir/template2/task-template-instantiate.sh -T templates_dir -t template2 new-dir
