#!/usr/bin/env bash

set -euo pipefail

set -a

_TPS_TESTS_DIR="$(dirname "$0")"

_TT_UTILS_DIR="${_TPS_TESTS_DIR}/utils"
source "${_TT_UTILS_DIR}/all.sh"

set +a

_TT_exit_code=0
bash "$@" || _TT_exit_code=$?
if [ "${_TT_exit_code}" -eq 0 ]; then
	_TT_errcho "OK"
else
	_TT_errcho "FAILED"
fi

exit "${_TT_exit_code}"
