# Do not edit this file manually. It is automatically generated.
# Edit 'capture-all.sh' instead.


source ../../definitions.sh
source ../definitions.sh
source definitions.sh

_TT_check_stage_not_in_a_tps_repo


stage_dir stage
expect_exec -oempty -e "captured-data/k-0/stderr" -r 11 run_gprompt 1badvar cat A_prompt_message


stage_dir stage
expect_exec -oempty -e "captured-data/k-1/stderr" -r 11 run_gprompt my_var non_existing_cmd_123 A_prompt_message

stage_dir stage
expect_exec -oempty -e "captured-data/k-2/stderr" -r 11 run_gprompt my_var non_existing_cmd_123 A_prompt_message "a description"


stage_dir stage
expect_exec -ih hi -oh2 "my_var=" "hi" -eh2 "Template parameter 'my_var'..." "Enter any string:" run_gprompt my_var cat "Enter any string:"

stage_dir stage
expect_exec -ih hi -oh2 "my_var=" "hi" -eh2 "Template parameter 'my_var' (a description)..." "Enter some string:" run_gprompt my_var cat "Enter some string:" "a description"

stage_dir stage
expect_exec -ih "hey you" -oh2 "my_var=" "hey you" -eh2 "Template parameter 'my_var'..." "Enter some string:" run_gprompt my_var cat "Enter some string:"

stage_dir stage
expect_exec -ih "" -oh2 "my_var=" "" -eh2 "Template parameter 'my_var'..." "Enter any string:" run_gprompt my_var cat "Enter any string:"

stage_dir stage
expect_exec -oh2 "my_var=" "hello" -eh2 "Template parameter 'my_var'..." "Parameter 'my_var' has predefined value 'hello'." run_gprompt my_var cat "Enter any string:" -- -D my_var=hello

stage_dir stage
expect_exec -oh2 "my_var=" "hello" -eh2 "Template parameter 'my_var' (a description)..." "Parameter 'my_var' has predefined value 'hello'." run_gprompt my_var cat "Enter any string:" "a description" -- --define my_var=hello


stage_dir stage
expect_exec -ih bye -oh2 "my_var=" "bye" -eh2 "Template parameter 'my_var'..." "Enter a string of length at least 3:" run_gprompt my_var at_least_3_long_validation_command "Enter a string of length at least 3:"

stage_dir stage
expect_exec -ih2 hi "hey you" -oh2 "my_var=" "hey you" -e "captured-data/k-10/stderr" run_gprompt my_var at_least_3_long_validation_command "Enter a string of length at least 3:"

stage_dir stage
expect_exec -ih "h 3" -oh2 "my_var=" "h 3" -eh2 "Template parameter 'my_var'..." "Enter a string of length at least 3:" run_gprompt my_var at_least_3_long_validation_command "Enter a string of length at least 3:"

stage_dir stage
expect_exec -ih2 "" h3i -oh2 "my_var=" "h3i" -e "captured-data/k-12/stderr" run_gprompt my_var at_least_3_long_validation_command "Enter a string of length at least 3:"

stage_dir stage
expect_exec -ih3 "" t cool -oh2 "my_var=" "cool" -e "captured-data/k-13/stderr" run_gprompt my_var at_least_3_long_validation_command "Enter a string of length at least 3:"

stage_dir stage
expect_exec -oh2 "my_var=" "aaa" -eh2 "Template parameter 'my_var'..." "Parameter 'my_var' has predefined value 'aaa'." run_gprompt my_var at_least_3_long_validation_command "Enter a string of length at least 3:" -- --define my_var=aaa

stage_dir stage
expect_exec -ih bye -oh2 "my_var=" "bye" -e "captured-data/k-15/stderr" run_gprompt my_var at_least_3_long_validation_command "Enter a string of length at least 3:" -- -D my_var=aa


stage_dir stage
expect_exec -ih aab -oh2 "my_var=" "b" -eh2 "Template parameter 'my_var'..." "Enter a string starting with aa:" run_gprompt my_var remove_starting_aa_validation_command "Enter a string starting with aa:"

stage_dir stage
expect_exec -ih2 ab aabc -oh2 "my_var=" "bc" -e "captured-data/k-17/stderr" run_gprompt my_var remove_starting_aa_validation_command "Enter a string starting with aa:"

stage_dir stage
expect_exec -ih "aa c" -oh2 "my_var=" " c" -eh2 "Template parameter 'my_var'..." "Enter a string starting with aa:" run_gprompt my_var remove_starting_aa_validation_command "Enter a string starting with aa:"

stage_dir stage
expect_exec -ih2 "" aad -oh2 "my_var=" "d" -e "captured-data/k-19/stderr" run_gprompt my_var remove_starting_aa_validation_command "Enter a string starting with aa:"

stage_dir stage
expect_exec -ih3 "" ab aacool -oh2 "my_var=" "cool" -e "captured-data/k-20/stderr" run_gprompt my_var remove_starting_aa_validation_command "Enter a string starting with aa:"

stage_dir stage
expect_exec -oh2 "my_var=" "f" -eh2 "Template parameter 'my_var'..." "Parameter 'my_var' has predefined value 'aaf'." run_gprompt my_var remove_starting_aa_validation_command "Enter a string starting with aa:" -- --define my_var=aaf

stage_dir stage
expect_exec -ih aart -oh2 "my_var=" "rt" -e "captured-data/k-22/stderr" run_gprompt my_var remove_starting_aa_validation_command "Enter a string starting with aa:" -- -D my_var=cc
