# Do not edit this file manually. It is automatically generated.
# Edit 'capture-all.sh' instead.


source ../../definitions.sh
source ../definitions.sh
source definitions.sh

_TT_check_stage_not_in_a_tps_repo


stage_dir stage
expect_exec -f "output_dir" "captured-data/k-0/probed_files/0_output_dir" -oempty -e "captured-data/k-0/stderr" -r 11 run_move_func template1 "" move_dir_contents

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-1/probed_files/0_output_dir" -oempty -e "captured-data/k-1/stderr" -r 11 run_move_func template1 "" "move_dir_contents \"aa\""

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-2/probed_files/0_output_dir" -oempty -e "captured-data/k-2/stderr" -r 11 run_move_func template1 "" "move_dir_contents \"aa\" \"b\" \"extra\""

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-3/probed_files/0_output_dir" -oempty -e "captured-data/k-3/stderr" -r 12 run_move_func template1 "" "move_dir_contents \"non-exist\" \"b\""

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-4/probed_files/0_output_dir" -oempty -e "captured-data/k-4/stderr" -r 12 run_move_func template1 "" "move_dir_contents \"aa/ff\" \"b\""

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-5/probed_files/0_output_dir" -oempty -e "captured-data/k-5/stderr" -r 12 run_move_func template1 "" "move_dir_contents \"b\" \"non-exist\""

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-6/probed_files/0_output_dir" -oempty -e "captured-data/k-6/stderr" -r 12 run_move_func template1 "" "move_dir_contents \"b\" \"aa/ff\""

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-7/probed_files/0_output_dir" -oempty -e "captured-data/k-7/stderr" -r 12 run_move_func template1 "" "move_dir_contents \".hdir\" \".hdir\""

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-8/probed_files/0_output_dir" -oempty -e "captured-data/k-8/stderr" -r 12 run_move_func template1 "" "move_dir_contents \"b\" \"b\""

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-9/probed_files/0_output_dir" -oempty -e "captured-data/k-9/stderr" -r 12 run_move_func template1 "" "move_dir_contents \"aa\" \"aa\""

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-10/probed_files/0_output_dir" -oempty -e "captured-data/k-10/stderr" -r 12 run_move_func template1 "" "move_dir_contents \"aa\" \"aa/dd\""

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-11/probed_files/0_output_dir" -oempty -e "captured-data/k-11/stderr" -r 12 run_move_func template1 "" "move_dir_contents \"aa/dd\" \"aa/dd\""


stage_dir stage
expect_exec -f "output_dir" "captured-data/k-12/probed_files/0_output_dir" -oempty -e "captured-data/k-12/stderr" run_move_func template1 "" "move_dir_contents \".hdir\" \"b\""

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-13/probed_files/0_output_dir" -oempty -e "captured-data/k-13/stderr" run_move_func template1 "" "move_dir_contents \".hdir\" \"aa\""

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-14/probed_files/0_output_dir" -oempty -e "captured-data/k-14/stderr" run_move_func template1 "" "move_dir_contents \".hdir\" \"aa/dd\""

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-15/probed_files/0_output_dir" -oempty -e "captured-data/k-15/stderr" run_move_func template1 "" "move_dir_contents \"b\" \".hdir\""

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-16/probed_files/0_output_dir" -oempty -e "captured-data/k-16/stderr" run_move_func template1 "" "move_dir_contents \"b\" \"aa\""

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-17/probed_files/0_output_dir" -oempty -e "captured-data/k-17/stderr" run_move_func template1 "" "move_dir_contents \"b\" \"aa/dd\""

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-18/probed_files/0_output_dir" -oempty -e "captured-data/k-18/stderr" run_move_func template1 "" "move_dir_contents \"aa\" \".hdir\""

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-19/probed_files/0_output_dir" -oempty -e "captured-data/k-19/stderr" run_move_func template1 "" "move_dir_contents \"aa\" \"b\""

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-20/probed_files/0_output_dir" -oempty -e "captured-data/k-20/stderr" run_move_func template1 "" "move_dir_contents \"aa/dd\" \".hdir\""

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-21/probed_files/0_output_dir" -oempty -e "captured-data/k-21/stderr" run_move_func template1 "" "move_dir_contents \"aa/dd\" \"b\""

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-22/probed_files/0_output_dir" -oempty -e "captured-data/k-22/stderr" run_move_func template1 "" "move_dir_contents \"aa/dd\" \"aa\""

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-23/probed_files/0_output_dir" -oempty -e "captured-data/k-23/stderr" run_move_func template1 dest "move_dir_contents \".hdir\" \"dest\""

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-24/probed_files/0_output_dir" -oempty -e "captured-data/k-24/stderr" run_move_func template1 dest "move_dir_contents \"b\" \"dest\""

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-25/probed_files/0_output_dir" -oempty -e "captured-data/k-25/stderr" run_move_func template1 dest "move_dir_contents \"aa\" \"dest\""

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-26/probed_files/0_output_dir" -oempty -e "captured-data/k-26/stderr" run_move_func template1 dest "move_dir_contents \"aa/dd\" \"dest\""


stage_dir stage
expect_exec -fu "output_dir" -f "templates_dir/template2/dir1" "captured-data/k-27/probed_files/1_templates_dir_dir1" -f "templates_dir/template2/dir2" "captured-data/k-27/probed_files/2_templates_dir_dir2" -oempty -e "captured-data/k-27/stderr" -r 12 run_move_func template2 "" "move_dir_contents \"dir1\" \"dir2\""
