# Do not edit this file manually. It is automatically generated.
# Edit 'capture-all.sh' instead.

stage_dir stage-without-init

expect_exec -o "captured-data/no-cmd-wo/stdout" -eempty -r 1 tps
expect_exec -oh "The variable is ''." -eempty tps show

stage_dir stage-with-init

expect_exec -o "captured-data/no-cmd-w/stdout" -eempty -r 1 tps
expect_exec -oh "The variable is 'the_init_value'." -eempty tps show
