# Do not edit this file manually. It is automatically generated.
# Edit 'capture-all.sh' instead.

source ../definition_source_util_sh.sh

stage_dir stage
expect_exec -fempty-dir ".hdir" -oempty -eempty recreate_dir .hdir
expect_exec -fempty-dir "aa/dd" -oempty -eempty recreate_dir aa/dd
expect_exec -fempty-dir "aa/d-new" -oempty -eempty recreate_dir aa/d-new
expect_exec -fempty-dir "aa/.h2" -oempty -eempty recreate_dir aa/.h2
expect_exec -fempty-dir "aa" -oempty -eempty recreate_dir aa
expect_exec -fempty-dir "b" -oempty -eempty recreate_dir b
expect_exec -fempty-dir "a_new_dir" -oempty -eempty recreate_dir a_new_dir
expect_exec -fempty-dir "b1/b2" -oempty -eempty recreate_dir b1/b2
expect_exec -fempty-dir "c1/c2/c3" -oempty -eempty recreate_dir c1/c2/c3
expect_exec -fempty-dir "d1/.d2/d3/d4" -oempty -eempty recreate_dir d1/.d2/d3/d4
expect_exec -fempty-dir "d1/.d2/d5/d6" -oempty -eempty recreate_dir d1/.d2/d5/d6
run_in_stage mkdir e1
expect_exec -fempty-dir "e1" -oempty -eempty recreate_dir e1
run_in_stage mkdir .a_hidden_dir
expect_exec -fempty-dir ".a_hidden_dir" -oempty -eempty recreate_dir .a_hidden_dir

stage_dir stage
expect_exec -fempty-dir "aa" -oempty -eempty recreate_dir aa
expect_exec -fempty-dir "another_new_dir" -oempty -eempty recreate_dir another_new_dir
expect_exec -fempty-dir ".another_hidden_dir" -oempty -eempty recreate_dir .another_hidden_dir
