# Do not edit this file manually. It is automatically generated.
# Edit 'capture-all.sh' instead.

stage_dir stage

expect_exec -o "captured-data/no-cmd/stdout" -eempty -r 1 tps
expect_exec -d a_dir -o "captured-data/no-cmd-d/stdout" -eempty -r 1 tps
expect_exec -oempty -eh "Error: Not in a TPS repository ('problem.json' not found in any of the parent directories)." -r 2 tps a_command
expect_exec -d a_dir -oempty -eh "Error: Not in a TPS repository ('problem.json' not found in any of the parent directories)." -r 2 tps a_command
expect_exec -oempty -eh "Error: Not in a TPS repository ('problem.json' not found in any of the parent directories)." -r 2 tps a_command a_param
expect_exec -d a_dir -oempty -eh "Error: Not in a TPS repository ('problem.json' not found in any of the parent directories)." -r 2 tps a_command a_param

expect_exec -oempty -eempty tps_bc 1 0
expect_exec -oempty -eempty tps_bc 1 0 a_command
expect_exec -oempty -eempty tps_bc 1 1 a_command
expect_exec -oempty -eempty tps_bc 1 0 a_command a_param
expect_exec -oempty -eempty tps_bc 1 1 a_command a_param
