# Do not edit this file manually. It is automatically generated.
# Edit 'capture-all.sh' instead.

stage_dir stage

source ../definitions.sh
_TT_check_stage_not_in_a_tps_repo


unset TPS_TASK_TEMPLATES_PATH

expect_exec -oempty -e "captured-data/k-0/stderr" -r 2 tps init

expect_exec -oempty -e "captured-data/k-1/stderr" -r 14 tps init -T templates1 -t default new_dir
expect_exec -oempty -e "captured-data/k-2/stderr" -r 2 tps init -T templates1 -t default new_dir another_arg
expect_exec -oempty -eh "Error: Given output directory 'another_dir' already exists." -r 4 tps init -T templates1 -t default another_dir
expect_exec -oempty -eh "Error: Given output directory 'another_file' already exists." -r 4 tps init -T templates1 -t default another_file

expect_exec -oempty -e "captured-data/k-5/stderr" -r 2 tps init new_dir -T
expect_exec -oempty -e "captured-data/k-6/stderr" -r 2 tps init new_dir -T ""
expect_exec -oempty -eh "Error: Given task templates directory 'nowhere' does not exist." -r 4 tps init new_dir -T nowhere
expect_exec -oempty -eh "Error: Given task templates directory 'another_file' is not a valid directory." -r 4 tps init new_dir -T another_file
expect_exec -oempty -e "captured-data/k-9/stderr" -r 2 tps init new_dir --templates-dir
expect_exec -oempty -e "captured-data/k-10/stderr" -r 2 tps init new_dir --templates-dir=
expect_exec -oempty -eh "Error: Given task templates directory 'nowhere' does not exist." -r 4 tps init new_dir --templates-dir=nowhere
expect_exec -oempty -eh "Error: Given task templates directory 'another_file' is not a valid directory." -r 4 tps init new_dir --templates-dir=another_file
expect_exec -oempty -e "captured-data/k-13/stderr" -r 2 tps init new_dir -t
expect_exec -oempty -e "captured-data/k-14/stderr" -r 2 tps init new_dir -t ""
expect_exec -oempty -e "captured-data/k-15/stderr" -r 2 tps init new_dir --template
expect_exec -oempty -e "captured-data/k-16/stderr" -r 2 tps init new_dir --template=
expect_exec -oempty -e "captured-data/k-17/stderr" -r 2 tps init new_dir -T templates1 --template
expect_exec -oempty -e "captured-data/k-18/stderr" -r 2 tps init new_dir -T templates1 --template=
expect_exec -oempty -e "captured-data/k-19/stderr" -r 2 tps init new_dir -T templates1 -t
expect_exec -oempty -e "captured-data/k-20/stderr" -r 2 tps init new_dir -T templates1 -t ""

expect_exec -oempty -e "captured-data/k-21/stderr" -r 2 tps init new_dir
expect_exec -oempty -e "captured-data/k-22/stderr" -r 2 tps init new_dir -t default
expect_exec -oempty -e "captured-data/k-23/stderr" -r 2 tps init new_dir -t tpl1
expect_exec -oempty -e "captured-data/k-24/stderr" -r 2 tps init new_dir -t file_x
expect_exec -oempty -e "captured-data/k-25/stderr" -r 2 tps init new_dir -t tpl2

expect_exec -oempty -e "captured-data/k-26/stderr" -r 2 tps init new_dir --template=default
expect_exec -oempty -e "captured-data/k-27/stderr" -r 2 tps init new_dir --template=tpl1
expect_exec -oempty -e "captured-data/k-28/stderr" -r 2 tps init new_dir --template=file_x
expect_exec -oempty -e "captured-data/k-29/stderr" -r 2 tps init new_dir --template=tpl2

expect_exec -oempty -e "captured-data/k-30/stderr" -r 14 tps init new_dir -T templates1
expect_exec -oempty -eh "Error: Given task templates directory 'z' does not exist." -r 4 tps init new_dir -T z
expect_exec -oempty -e "captured-data/k-32/stderr" -r 14 tps init new_dir --templates-dir=templates1
expect_exec -oempty -eh "Error: Given task templates directory 'z' does not exist." -r 4 tps init new_dir --templates-dir=z

expect_exec -oempty -e "captured-data/k-34/stderr" -r 14 tps init new_dir -T templates1
expect_exec -oempty -e "captured-data/k-35/stderr" -r 14 tps init new_dir -T templates1 -t default
expect_exec -oempty -e "captured-data/k-36/stderr" -r 14 tps init new_dir -T templates1 -t tpl1
expect_exec -oempty -eh "Error: Task template 'file_x' in 'templates1' is not a valid directory." -r 4 tps init new_dir -T templates1 -t file_x
expect_exec -oempty -eh "Error: Task template 'z' does not exist in 'templates1'." -r 4 tps init new_dir -T templates1 -t z

expect_exec -oempty -e "captured-data/k-39/stderr" -r 14 tps init new_dir -T templates1 --template=default
expect_exec -oempty -e "captured-data/k-40/stderr" -r 14 tps init new_dir -T templates1 --template=tpl1
expect_exec -oempty -eh "Error: Task template 'file_x' in 'templates1' is not a valid directory." -r 4 tps init new_dir -T templates1 --template=file_x
expect_exec -oempty -eh "Error: Task template 'z' does not exist in 'templates1'." -r 4 tps init new_dir -T templates1 --template=z

export TPS_TASK_TEMPLATES_PATH=nowhere

expect_exec -oempty -e "captured-data/k-43/stderr" -r 14 tps init new_dir -T templates1
expect_exec -oempty -eh "Error: Given task templates directory 'z' does not exist." -r 4 tps init new_dir -T z
expect_exec -oempty -e "captured-data/k-45/stderr" -r 14 tps init new_dir --templates-dir=templates1
expect_exec -oempty -eh "Error: Given task templates directory 'z' does not exist." -r 4 tps init new_dir --templates-dir=z

expect_exec -oempty -e "captured-data/k-47/stderr" -r 14 tps init new_dir -T templates1
expect_exec -oempty -e "captured-data/k-48/stderr" -r 14 tps init new_dir -T templates1 -t default
expect_exec -oempty -e "captured-data/k-49/stderr" -r 14 tps init new_dir -T templates1 -t tpl1
expect_exec -oempty -eh "Error: Task template 'file_x' in 'templates1' is not a valid directory." -r 4 tps init new_dir -T templates1 -t file_x
expect_exec -oempty -eh "Error: Task template 'z' does not exist in 'templates1'." -r 4 tps init new_dir -T templates1 -t z

expect_exec -oempty -e "captured-data/k-52/stderr" -r 14 tps init new_dir -T templates1 --template=default
expect_exec -oempty -e "captured-data/k-53/stderr" -r 14 tps init new_dir -T templates1 --template=tpl1
expect_exec -oempty -eh "Error: Task template 'file_x' in 'templates1' is not a valid directory." -r 4 tps init new_dir -T templates1 --template=file_x
expect_exec -oempty -eh "Error: Task template 'z' does not exist in 'templates1'." -r 4 tps init new_dir -T templates1 --template=z

export TPS_TASK_TEMPLATES_PATH=templates1

expect_exec -oempty -e "captured-data/k-56/stderr" -r 14 tps init new_dir
expect_exec -oempty -e "captured-data/k-57/stderr" -r 14 tps init new_dir -t default
expect_exec -oempty -e "captured-data/k-58/stderr" -r 14 tps init new_dir -t tpl1
expect_exec -oempty -e "captured-data/k-59/stderr" -r 4 tps init new_dir -t file_x
expect_exec -oempty -e "captured-data/k-60/stderr" -r 4 tps init new_dir -t tpl2

expect_exec -oempty -e "captured-data/k-61/stderr" -r 14 tps init new_dir --template=default
expect_exec -oempty -e "captured-data/k-62/stderr" -r 14 tps init new_dir --template=tpl1
expect_exec -oempty -e "captured-data/k-63/stderr" -r 4 tps init new_dir --template=file_x
expect_exec -oempty -e "captured-data/k-64/stderr" -r 4 tps init new_dir --template=tpl2

export TPS_TASK_TEMPLATES_PATH=templates2

expect_exec -oempty -e "captured-data/k-65/stderr" -r 4 tps init new_dir
expect_exec -oempty -e "captured-data/k-66/stderr" -r 4 tps init new_dir -t default
expect_exec -oempty -e "captured-data/k-67/stderr" -r 4 tps init new_dir -t tpl1
expect_exec -oempty -e "captured-data/k-68/stderr" -r 4 tps init new_dir -t file_x
expect_exec -oempty -e "captured-data/k-69/stderr" -r 14 tps init new_dir -t tpl2

expect_exec -oempty -e "captured-data/k-70/stderr" -r 4 tps init new_dir --template=default
expect_exec -oempty -e "captured-data/k-71/stderr" -r 4 tps init new_dir --template=tpl1
expect_exec -oempty -e "captured-data/k-72/stderr" -r 4 tps init new_dir --template=file_x
expect_exec -oempty -e "captured-data/k-73/stderr" -r 14 tps init new_dir --template=tpl2

export TPS_TASK_TEMPLATES_PATH=templates1:templates2

expect_exec -oempty -e "captured-data/k-74/stderr" -r 14 tps init new_dir
expect_exec -oempty -e "captured-data/k-75/stderr" -r 14 tps init new_dir -t default
expect_exec -oempty -e "captured-data/k-76/stderr" -r 14 tps init new_dir -t tpl1
expect_exec -oempty -e "captured-data/k-77/stderr" -r 4 tps init new_dir -t file_x
expect_exec -oempty -e "captured-data/k-78/stderr" -r 14 tps init new_dir -t tpl2

expect_exec -oempty -e "captured-data/k-79/stderr" -r 14 tps init new_dir --template=default
expect_exec -oempty -e "captured-data/k-80/stderr" -r 14 tps init new_dir --template=tpl1
expect_exec -oempty -e "captured-data/k-81/stderr" -r 4 tps init new_dir --template=file_x
expect_exec -oempty -e "captured-data/k-82/stderr" -r 14 tps init new_dir --template=tpl2
