# Do not edit this file manually. It is automatically generated.
# Edit 'capture-all.sh' instead.

stage_dir stage

source ../definitions.sh
_TT_check_stage_not_in_a_tps_repo


unset TPS_TASK_TEMPLATES_PATH

expect_exec -oh "init " -eempty tps_bc 1 0 init
expect_exec -oh "init " -eempty tps_bc 1 1 init
expect_exec -oh "init " -eempty tps_bc 1 2 init
expect_exec -oempty -eempty tps_bc 2 0 init
expect_exec -oempty -eempty tps_bc 2 0 init a
expect_exec -oempty -eempty tps_bc 2 0 init --template=
expect_exec -oempty -eempty tps_bc 2 1 init --template=
expect_exec -oh3 "--template=" "--templates-dir=" "--define " -eempty tps_bc 2 2 init --template=
expect_exec -oh2 "--template=" "--templates-dir=" -eempty tps_bc 2 3 init --template=
expect_exec -oh2 "--template=" "--templates-dir=" -eempty tps_bc 2 9 init --template=
expect_exec -oh2 "--template=" "--templates-dir=" -eempty tps_bc 2 10 init --template=
expect_exec -oempty -eempty tps_bc 2 0 init --templates-dir=
expect_exec -oempty -eempty tps_bc 2 1 init --templates-dir=
expect_exec -oh3 "--template=" "--templates-dir=" "--define " -eempty tps_bc 2 2 init --templates-dir=
expect_exec -oh2 "--template=" "--templates-dir=" -eempty tps_bc 2 3 init --templates-dir=
expect_exec -oh2 "--template=" "--templates-dir=" -eempty tps_bc 2 10 init --templates-dir=
expect_exec -oh "--templates-dir=" -eempty tps_bc 2 11 init --templates-dir=
expect_exec -oempty -eempty tps_bc 2 0 init --define
expect_exec -oempty -eempty tps_bc 2 1 init --define
expect_exec -oh3 "--template=" "--templates-dir=" "--define " -eempty tps_bc 2 2 init --define
expect_exec -oh "--define " -eempty tps_bc 2 3 init --define
expect_exec -oh "--define " -eempty tps_bc 2 6 init --define
expect_exec -oh "--define " -eempty tps_bc 2 7 init --define

expect_exec -oempty -eempty tps_bc 3 0 init -t
expect_exec -oempty -eempty tps_bc 3 0 init -t tpl1
expect_exec -oempty -eempty tps_bc 3 1 init -t tpl1
expect_exec -oempty -eempty tps_bc 3 4 init -t tpl1
expect_exec -oempty -eempty tps_bc 3 1 init -t d
expect_exec -oempty -eempty tps_bc 3 1 init -t z

expect_exec -oempty -eempty tps_bc 2 11 init --template=tpl1
expect_exec -oempty -eempty tps_bc 2 12 init --template=tpl1
expect_exec -oempty -eempty tps_bc 2 15 init --template=tpl1
expect_exec -oempty -eempty tps_bc 2 12 init --template=d
expect_exec -oempty -eempty tps_bc 2 12 init --template=z

expect_exec -oh2 "templates1/" "templates2/" -eempty tps_bc 3 0 init -T
expect_exec -oh2 "templates1/" "templates2/" -eempty tps_bc 3 0 init -T templates1
expect_exec -oh2 "templates1/" "templates2/" -eempty tps_bc 3 1 init -T templates1
expect_exec -oh2 "templates1/" "templates2/" -eempty tps_bc 3 2 init -T templates1
expect_exec -oh2 "templates1/" "templates2/" -eempty tps_bc 3 9 init -T templates1
expect_exec -oh "templates1/" -eempty tps_bc 3 10 init -T templates1
expect_exec -oempty -eempty tps_bc 3 1 init -T z

expect_exec -oh2 "templates1/" "templates2/" -eempty tps_bc 2 16 init --templates-dir=templates1
expect_exec -oh2 "templates1/" "templates2/" -eempty tps_bc 2 17 init --templates-dir=templates1
expect_exec -oh2 "templates1/" "templates2/" -eempty tps_bc 2 18 init --templates-dir=templates1
expect_exec -oh2 "templates1/" "templates2/" -eempty tps_bc 2 25 init --templates-dir=templates1
expect_exec -oh "templates1/" -eempty tps_bc 2 26 init --templates-dir=templates1
expect_exec -oempty -eempty tps_bc 2 17 init --templates-dir=z

expect_exec -oh2 "default " "tpl1 " -eempty tps_bc 5 0 init -T templates1 -t
expect_exec -oh2 "default " "tpl1 " -eempty tps_bc 5 0 init -T templates1 -t tpl1
expect_exec -oh "tpl1 " -eempty tps_bc 5 1 init -T templates1 -t tpl1
expect_exec -oh "tpl1 " -eempty tps_bc 5 4 init -T templates1 -t tpl1
expect_exec -oh "default " -eempty tps_bc 5 1 init -T templates1 -t d
expect_exec -oempty -eempty tps_bc 5 1 init -T templates1 -t z

expect_exec -oh2 "default " "tpl1 " -eempty tps_bc 4 11 init -T templates1 --template=tpl1
expect_exec -oh "tpl1 " -eempty tps_bc 4 12 init -T templates1 --template=tpl1
expect_exec -oh "tpl1 " -eempty tps_bc 4 15 init -T templates1 --template=tpl1
expect_exec -oh "default " -eempty tps_bc 4 12 init -T templates1 --template=d
expect_exec -oempty -eempty tps_bc 4 12 init -T templates1 --template=z

expect_exec -oh "tpl2 " -eempty tps_bc 5 0 init -T templates2 -t
expect_exec -oh "tpl2 " -eempty tps_bc 5 0 init -T templates2 -t tpl1
expect_exec -oh "tpl2 " -eempty tps_bc 5 1 init -T templates2 -t tpl1
expect_exec -oempty -eempty tps_bc 5 4 init -T templates2 -t tpl1
expect_exec -oempty -eempty tps_bc 5 1 init -T templates2 -t d
expect_exec -oempty -eempty tps_bc 5 1 init -T templates2 -t z

expect_exec -oh "tpl2 " -eempty tps_bc 4 11 init -T templates2 --template=tpl1
expect_exec -oh "tpl2 " -eempty tps_bc 4 12 init -T templates2 --template=tpl1
expect_exec -oempty -eempty tps_bc 4 15 init -T templates2 --template=tpl1
expect_exec -oempty -eempty tps_bc 4 12 init -T templates2 --template=d
expect_exec -oempty -eempty tps_bc 4 12 init -T templates2 --template=z

export TPS_TASK_TEMPLATES_PATH=nowhere

expect_exec -oempty -eempty tps_bc 3 0 init -t
expect_exec -oempty -eempty tps_bc 3 0 init -t tpl1
expect_exec -oempty -eempty tps_bc 3 1 init -t tpl1
expect_exec -oempty -eempty tps_bc 3 4 init -t tpl1
expect_exec -oempty -eempty tps_bc 3 1 init -t d
expect_exec -oempty -eempty tps_bc 3 1 init -t z

expect_exec -oempty -eempty tps_bc 2 11 init --template=tpl1
expect_exec -oempty -eempty tps_bc 2 12 init --template=tpl1
expect_exec -oempty -eempty tps_bc 2 15 init --template=tpl1
expect_exec -oempty -eempty tps_bc 2 12 init --template=d
expect_exec -oempty -eempty tps_bc 2 12 init --template=z

expect_exec -oh2 "templates1/" "templates2/" -eempty tps_bc 3 0 init -T
expect_exec -oh2 "templates1/" "templates2/" -eempty tps_bc 3 0 init -T templates1
expect_exec -oh2 "templates1/" "templates2/" -eempty tps_bc 3 1 init -T templates1
expect_exec -oh2 "templates1/" "templates2/" -eempty tps_bc 3 2 init -T templates1
expect_exec -oh2 "templates1/" "templates2/" -eempty tps_bc 3 9 init -T templates1
expect_exec -oh "templates1/" -eempty tps_bc 3 10 init -T templates1
expect_exec -oempty -eempty tps_bc 3 1 init -T z

expect_exec -oh2 "templates1/" "templates2/" -eempty tps_bc 2 16 init --templates-dir=templates1
expect_exec -oh2 "templates1/" "templates2/" -eempty tps_bc 2 17 init --templates-dir=templates1
expect_exec -oh2 "templates1/" "templates2/" -eempty tps_bc 2 18 init --templates-dir=templates1
expect_exec -oh2 "templates1/" "templates2/" -eempty tps_bc 2 25 init --templates-dir=templates1
expect_exec -oh "templates1/" -eempty tps_bc 2 26 init --templates-dir=templates1
expect_exec -oempty -eempty tps_bc 2 17 init --templates-dir=z

expect_exec -oh2 "default " "tpl1 " -eempty tps_bc 5 0 init -T templates1 -t
expect_exec -oh2 "default " "tpl1 " -eempty tps_bc 5 0 init -T templates1 -t tpl1
expect_exec -oh "tpl1 " -eempty tps_bc 5 1 init -T templates1 -t tpl1
expect_exec -oh "tpl1 " -eempty tps_bc 5 4 init -T templates1 -t tpl1
expect_exec -oh "default " -eempty tps_bc 5 1 init -T templates1 -t d
expect_exec -oempty -eempty tps_bc 5 1 init -T templates1 -t z

expect_exec -oh2 "default " "tpl1 " -eempty tps_bc 4 11 init -T templates1 --template=tpl1
expect_exec -oh "tpl1 " -eempty tps_bc 4 12 init -T templates1 --template=tpl1
expect_exec -oh "tpl1 " -eempty tps_bc 4 15 init -T templates1 --template=tpl1
expect_exec -oh "default " -eempty tps_bc 4 12 init -T templates1 --template=d
expect_exec -oempty -eempty tps_bc 4 12 init -T templates1 --template=z

expect_exec -oh "tpl2 " -eempty tps_bc 5 0 init -T templates2 -t
expect_exec -oh "tpl2 " -eempty tps_bc 5 0 init -T templates2 -t tpl1
expect_exec -oh "tpl2 " -eempty tps_bc 5 1 init -T templates2 -t tpl1
expect_exec -oempty -eempty tps_bc 5 4 init -T templates2 -t tpl1
expect_exec -oempty -eempty tps_bc 5 1 init -T templates2 -t d
expect_exec -oempty -eempty tps_bc 5 1 init -T templates2 -t z

expect_exec -oh "tpl2 " -eempty tps_bc 4 11 init -T templates2 --template=tpl1
expect_exec -oh "tpl2 " -eempty tps_bc 4 12 init -T templates2 --template=tpl1
expect_exec -oempty -eempty tps_bc 4 15 init -T templates2 --template=tpl1
expect_exec -oempty -eempty tps_bc 4 12 init -T templates2 --template=d
expect_exec -oempty -eempty tps_bc 4 12 init -T templates2 --template=z

export TPS_TASK_TEMPLATES_PATH=templates1

expect_exec -oh2 "default " "tpl1 " -eempty tps_bc 3 0 init -t
expect_exec -oh2 "default " "tpl1 " -eempty tps_bc 3 0 init -t tpl1
expect_exec -oh "tpl1 " -eempty tps_bc 3 1 init -t tpl1
expect_exec -oh "tpl1 " -eempty tps_bc 3 4 init -t tpl1
expect_exec -oh "default " -eempty tps_bc 3 1 init -t d
expect_exec -oempty -eempty tps_bc 3 1 init -t z

expect_exec -oh2 "default " "tpl1 " -eempty tps_bc 2 11 init --template=tpl1
expect_exec -oh "tpl1 " -eempty tps_bc 2 12 init --template=tpl1
expect_exec -oh "tpl1 " -eempty tps_bc 2 15 init --template=tpl1
expect_exec -oh "default " -eempty tps_bc 2 12 init --template=d
expect_exec -oempty -eempty tps_bc 2 12 init --template=z

export TPS_TASK_TEMPLATES_PATH=templates2

expect_exec -oh "tpl2 " -eempty tps_bc 3 0 init -t
expect_exec -oh "tpl2 " -eempty tps_bc 3 0 init -t tpl1
expect_exec -oh "tpl2 " -eempty tps_bc 3 1 init -t tpl1
expect_exec -oempty -eempty tps_bc 3 4 init -t tpl1
expect_exec -oempty -eempty tps_bc 3 1 init -t d
expect_exec -oempty -eempty tps_bc 3 1 init -t z

expect_exec -oh "tpl2 " -eempty tps_bc 2 11 init --template=tpl1
expect_exec -oh "tpl2 " -eempty tps_bc 2 12 init --template=tpl1
expect_exec -oempty -eempty tps_bc 2 15 init --template=tpl1
expect_exec -oempty -eempty tps_bc 2 12 init --template=d
expect_exec -oempty -eempty tps_bc 2 12 init --template=z

export TPS_TASK_TEMPLATES_PATH=templates1:templates2

expect_exec -oh3 "default " "tpl1 " "tpl2 " -eempty tps_bc 3 0 init -t
expect_exec -oh3 "default " "tpl1 " "tpl2 " -eempty tps_bc 3 0 init -t tpl1
expect_exec -oh2 "tpl1 " "tpl2 " -eempty tps_bc 3 1 init -t tpl1
expect_exec -oh "tpl1 " -eempty tps_bc 3 4 init -t tpl1
expect_exec -oh "default " -eempty tps_bc 3 1 init -t d
expect_exec -oempty -eempty tps_bc 3 1 init -t z

expect_exec -oh3 "default " "tpl1 " "tpl2 " -eempty tps_bc 2 11 init --template=tpl1
expect_exec -oh2 "tpl1 " "tpl2 " -eempty tps_bc 2 12 init --template=tpl1
expect_exec -oh "tpl1 " -eempty tps_bc 2 15 init --template=tpl1
expect_exec -oh "default " -eempty tps_bc 2 12 init --template=d
expect_exec -oempty -eempty tps_bc 2 12 init --template=z
