# Do not edit this file manually. It is automatically generated.
# Edit 'capture-all.sh' instead.


source ../../definitions.sh
source ../definitions.sh
source definitions.sh

_TT_check_stage_not_in_a_tps_repo


stage_dir stage
expect_exec -f "output_dir" "captured-data/k-0/probed_files/0_output_dir" -oempty -e "captured-data/k-0/stderr" -r 11 run_select_func template1 "prompt string myvar" select_file_by_value -- -D myvar=aaa

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-1/probed_files/0_output_dir" -oempty -e "captured-data/k-1/stderr" -r 11 run_select_func template1 "prompt string myvar" "select_file_by_value \"\${myvar}\"" -- -D myvar=aaa

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-2/probed_files/0_output_dir" -oempty -e "captured-data/k-2/stderr" run_select_func template1 "prompt string myvar" "select_file_by_value \"\${myvar}\" \"dest\"" -- -D myvar=aaa

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-3/probed_files/0_output_dir" -oempty -e "captured-data/k-3/stderr" -r 11 run_select_func template1 "prompt string myvar" "select_file_by_value \"\${myvar}\" \"dest\" \"x\"" -- -D myvar=aaa

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-4/probed_files/0_output_dir" -oempty -e "captured-data/k-4/stderr" -r 12 run_select_func template1 "prompt string myvar" "select_file_by_value \"\${myvar}\" \"b\" \"aaa\" \"aa\"" -- -D myvar=aaa

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-5/probed_files/0_output_dir" -oempty -e "captured-data/k-5/stderr" -r 14 run_select_func template1 "prompt string myvar" "select_file_by_value \"\${myvar}\" \"dest\" \"aaa\" \"non-exist\"" -- -D myvar=aaa

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-6/probed_files/0_output_dir" -oempty -e "captured-data/k-6/stderr" -r 12 run_select_func template1 "prompt string myvar" "select_file_by_value \"\${myvar}\" \"dest\" \"aaa\" \"aa\" \"aaa\" \"b\"" -- -D myvar=aaa

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-7/probed_files/0_output_dir" -oempty -e "captured-data/k-7/stderr" -r 12 run_select_func template1 "prompt string myvar" "select_file_by_value \"\${myvar}\" \"dest\" \"aaa\" \"aa\" \"bbb\" \"aa\"" -- -D myvar=aaa

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-8/probed_files/0_output_dir" -oempty -e "captured-data/k-8/stderr" run_select_func template1 "prompt string myvar" "select_file_by_value \"\${myvar}\" \"dest\" \"aaa\" \"aa\" \"bbb\" \"b\"" -- -D myvar=aaa

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-9/probed_files/0_output_dir" -oempty -e "captured-data/k-9/stderr" run_select_func template1 "prompt string myvar" "select_file_by_value \"\${myvar}\" \"dest\" \"aaa\" \"aa\" \"bbb\" \"b\"" -- -D myvar=bbb

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-10/probed_files/0_output_dir" -oempty -e "captured-data/k-10/stderr" run_select_func template1 "prompt string myvar" "select_file_by_value \"\${myvar}\" \"dest\" \"aaa\" \"aa\" \"bbb\" \"b\"" -- -D myvar=oo


stage_dir stage
expect_exec -f "output_dir" "captured-data/k-11/probed_files/0_output_dir" -oempty -e "captured-data/k-11/stderr" run_select_func template1 "prompt string myvar" "select_file_by_value \"\${myvar}\" \"dest\" \"ad\" \"aa\" \"bd\" \"b\" \"hd\" \".hdir\" \"hf\" \".h.txt\" \"tf\" \"t.txt\"" -- -D myvar=ad

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-12/probed_files/0_output_dir" -oempty -e "captured-data/k-12/stderr" run_select_func template1 "prompt string myvar" "select_file_by_value \"\${myvar}\" \"dest\" \"ad\" \"aa\" \"bd\" \"b\" \"hd\" \".hdir\" \"hf\" \".h.txt\" \"tf\" \"t.txt\"" -- -D myvar=bd

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-13/probed_files/0_output_dir" -oempty -e "captured-data/k-13/stderr" run_select_func template1 "prompt string myvar" "select_file_by_value \"\${myvar}\" \"dest\" \"ad\" \"aa\" \"bd\" \"b\" \"hd\" \".hdir\" \"hf\" \".h.txt\" \"tf\" \"t.txt\"" -- -D myvar=hd

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-14/probed_files/0_output_dir" -oempty -e "captured-data/k-14/stderr" run_select_func template1 "prompt string myvar" "select_file_by_value \"\${myvar}\" \"dest\" \"ad\" \"aa\" \"bd\" \"b\" \"hd\" \".hdir\" \"hf\" \".h.txt\" \"tf\" \"t.txt\"" -- -D myvar=hf

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-15/probed_files/0_output_dir" -oempty -e "captured-data/k-15/stderr" run_select_func template1 "prompt string myvar" "select_file_by_value \"\${myvar}\" \"dest\" \"ad\" \"aa\" \"bd\" \"b\" \"hd\" \".hdir\" \"hf\" \".h.txt\" \"tf\" \"t.txt\"" -- -D myvar=tf

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-16/probed_files/0_output_dir" -oempty -e "captured-data/k-16/stderr" run_select_func template1 "prompt string myvar" "select_file_by_value \"\${myvar}\" \"dest\" \"ad\" \"aa\" \"bd\" \"b\" \"hd\" \".hdir\" \"hf\" \".h.txt\" \"tf\" \"t.txt\"" -- -D myvar=oo


stage_dir stage
expect_exec -f "output_dir" "captured-data/k-17/probed_files/0_output_dir" -oempty -e "captured-data/k-17/stderr" run_select_func template1 "prompt string myvar" "select_file_by_value \"\${myvar}\" \"aa/dest\" \"ad\" \"aa/dd\" \"ah\" \"aa/.hh\" \"af1\" \"aa/f1.in\" \"aff\" \"aa/ff\" \"ay\" \"aa/y.txt\" \"bd\" \"b\" \"t\" \"t.txt\"" -- -D myvar=ad

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-18/probed_files/0_output_dir" -oempty -e "captured-data/k-18/stderr" run_select_func template1 "prompt string myvar" "select_file_by_value \"\${myvar}\" \"aa/dest\" \"ad\" \"aa/dd\" \"ah\" \"aa/.hh\" \"af1\" \"aa/f1.in\" \"aff\" \"aa/ff\" \"ay\" \"aa/y.txt\" \"bd\" \"b\" \"t\" \"t.txt\"" -- -D myvar=ah

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-19/probed_files/0_output_dir" -oempty -e "captured-data/k-19/stderr" run_select_func template1 "prompt string myvar" "select_file_by_value \"\${myvar}\" \"aa/dest\" \"ad\" \"aa/dd\" \"ah\" \"aa/.hh\" \"af1\" \"aa/f1.in\" \"aff\" \"aa/ff\" \"ay\" \"aa/y.txt\" \"bd\" \"b\" \"t\" \"t.txt\"" -- -D myvar=af1

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-20/probed_files/0_output_dir" -oempty -e "captured-data/k-20/stderr" run_select_func template1 "prompt string myvar" "select_file_by_value \"\${myvar}\" \"aa/dest\" \"ad\" \"aa/dd\" \"ah\" \"aa/.hh\" \"af1\" \"aa/f1.in\" \"aff\" \"aa/ff\" \"ay\" \"aa/y.txt\" \"bd\" \"b\" \"t\" \"t.txt\"" -- -D myvar=aff

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-21/probed_files/0_output_dir" -oempty -e "captured-data/k-21/stderr" run_select_func template1 "prompt string myvar" "select_file_by_value \"\${myvar}\" \"aa/dest\" \"ad\" \"aa/dd\" \"ah\" \"aa/.hh\" \"af1\" \"aa/f1.in\" \"aff\" \"aa/ff\" \"ay\" \"aa/y.txt\" \"bd\" \"b\" \"t\" \"t.txt\"" -- -D myvar=ay

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-22/probed_files/0_output_dir" -oempty -e "captured-data/k-22/stderr" run_select_func template1 "prompt string myvar" "select_file_by_value \"\${myvar}\" \"aa/dest\" \"ad\" \"aa/dd\" \"ah\" \"aa/.hh\" \"af1\" \"aa/f1.in\" \"aff\" \"aa/ff\" \"ay\" \"aa/y.txt\" \"bd\" \"b\" \"t\" \"t.txt\"" -- -D myvar=bd

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-23/probed_files/0_output_dir" -oempty -e "captured-data/k-23/stderr" run_select_func template1 "prompt string myvar" "select_file_by_value \"\${myvar}\" \"aa/dest\" \"ad\" \"aa/dd\" \"ah\" \"aa/.hh\" \"af1\" \"aa/f1.in\" \"aff\" \"aa/ff\" \"ay\" \"aa/y.txt\" \"bd\" \"b\" \"t\" \"t.txt\"" -- -D myvar=t

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-24/probed_files/0_output_dir" -oempty -e "captured-data/k-24/stderr" run_select_func template1 "prompt string myvar" "select_file_by_value \"\${myvar}\" \"aa/dest\" \"ad\" \"aa/dd\" \"ah\" \"aa/.hh\" \"af1\" \"aa/f1.in\" \"aff\" \"aa/ff\" \"ay\" \"aa/y.txt\" \"bd\" \"b\" \"t\" \"t.txt\"" -- -D myvar=qq


stage_dir stage
expect_exec -fu "output_dir" -f "templates_dir/template2/dir1" "captured-data/k-25/probed_files/1_templates_dir_dir1" -f "templates_dir/template2/dir2" "captured-data/k-25/probed_files/2_templates_dir_dir2" -fu "templates_dir/template2/dest" -oempty -e "captured-data/k-25/stderr" -r 12 run_select_func template2 "" "select_file_by_value \"a\" \"dest\" \"a\" \"dir1\" \"b\" \"dir2\""
