# Do not edit this file manually. It is automatically generated.
# Edit 'capture-all.sh' instead.


source ../../definitions.sh
source ../definitions.sh
source definitions.sh

_TT_check_stage_not_in_a_tps_repo


stage_dir stage
expect_exec -f "output_dir" "captured-data/k-0/probed_files/0_output_dir" -oempty -e "captured-data/k-0/stderr" run_ttis templates_dir/template1/task-template-instantiate.sh -T templates_dir -t template1 output_dir


stage_dir stage
expect_exec -f "output_dir" "captured-data/k-1/probed_files/0_output_dir" -oempty -e "captured-data/k-1/stderr" -r 11 run_replace_func template2 "prompt string myvar" replace_in_file_names__unified -- -D myvar=trs2

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-2/probed_files/0_output_dir" -oempty -e "captured-data/k-2/stderr" -r 11 run_replace_func template2 "prompt string myvar" "replace_in_file_names__unified \"str1\"" -- -D myvar=trs2

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-3/probed_files/0_output_dir" -oempty -e "captured-data/k-3/stderr" run_replace_func template2 "prompt string myvar" "replace_in_file_names__unified \"str1\" \"\${myvar}\"" -- -D myvar=trs2

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-4/probed_files/0_output_dir" -oempty -e "captured-data/k-4/stderr" run_replace_func template2 "prompt string myvar" "replace_in_file_names__unified \"str1\" \"\${myvar}\" \"vis\"" -- -D myvar=trs2

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-5/probed_files/0_output_dir" -oempty -e "captured-data/k-5/stderr" -r 14 run_replace_func template2 "prompt string myvar" "replace_in_file_names__unified \"str1\" \"\${myvar}\" \"vis\" \"non-exist\"" -- -D myvar=trs2

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-6/probed_files/0_output_dir" -oempty -e "captured-data/k-6/stderr" run_replace_func template2 "prompt string myvar" "replace_in_file_names__unified \"str1\" \"\${myvar}\" \".\"" -- -D myvar=trs2

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-7/probed_files/0_output_dir" -oempty -e "captured-data/k-7/stderr" run_replace_func template2 "prompt string myvar" "replace_in_file_names__unified \"str1\" \"\${myvar}\" \"vis\" \".str1\"" -- -D myvar=trs.2

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-8/probed_files/0_output_dir" -oempty -e "captured-data/k-8/stderr" run_replace_func template2 "prompt string myvar" "replace_in_file_names__unified \"str1\" \"\${myvar}\" \".str1.py\" \"str1/.str1.sh\"" -- -D myvar=trs.2

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-9/probed_files/0_output_dir" -oempty -e "captured-data/k-9/stderr" run_replace_func template2 "prompt string myvar" "replace_in_file_names__unified \"str1.py\" \"\${myvar}\" \".\"" -- -D myvar=trs2.py


stage_dir stage
expect_exec -f "output_dir" "captured-data/k-10/probed_files/0_output_dir" -oempty -e "captured-data/k-10/stderr" -r 11 run_replace_func template2 "prompt string myvar" replace_in_file_contents__unified -- -D myvar=trs2

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-11/probed_files/0_output_dir" -oempty -e "captured-data/k-11/stderr" -r 11 run_replace_func template2 "prompt string myvar" "replace_in_file_contents__unified \"str1\"" -- -D myvar=trs2

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-12/probed_files/0_output_dir" -oempty -e "captured-data/k-12/stderr" run_replace_func template2 "prompt string myvar" "replace_in_file_contents__unified \"str1\" \"\${myvar}\"" -- -D myvar=trs2

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-13/probed_files/0_output_dir" -oempty -e "captured-data/k-13/stderr" run_replace_func template2 "prompt string myvar" "replace_in_file_contents__unified \"str1\" \"\${myvar}\" \"vis\"" -- -D myvar=trs2

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-14/probed_files/0_output_dir" -oempty -e "captured-data/k-14/stderr" -r 14 run_replace_func template2 "prompt string myvar" "replace_in_file_contents__unified \"str1\" \"\${myvar}\" \"vis\" \"non-exist\"" -- -D myvar=trs2

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-15/probed_files/0_output_dir" -oempty -e "captured-data/k-15/stderr" run_replace_func template2 "prompt string myvar" "replace_in_file_contents__unified \"str1\" \"\${myvar}\" \".\"" -- -D myvar=trs2

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-16/probed_files/0_output_dir" -oempty -e "captured-data/k-16/stderr" run_replace_func template2 "prompt string myvar" "replace_in_file_contents__unified \"str1\" \"\${myvar}\" \"vis\" \".str1\"" -- -D myvar=trs.2

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-17/probed_files/0_output_dir" -oempty -e "captured-data/k-17/stderr" run_replace_func template2 "prompt string myvar" "replace_in_file_contents__unified \"str1\" \"\${myvar}\" \".str1.py\" \"str1/.str1.sh\"" -- -D myvar=trs.2


stage_dir stage
expect_exec -f "output_dir" "captured-data/k-18/probed_files/0_output_dir" -oempty -e "captured-data/k-18/stderr" -r 11 run_replace_func template2 "prompt string myvar" replace_in_file_names_and_contents__unified -- -D myvar=trs2

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-19/probed_files/0_output_dir" -oempty -e "captured-data/k-19/stderr" -r 11 run_replace_func template2 "prompt string myvar" "replace_in_file_names_and_contents__unified \"str1\"" -- -D myvar=trs2

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-20/probed_files/0_output_dir" -oempty -e "captured-data/k-20/stderr" run_replace_func template2 "prompt string myvar" "replace_in_file_names_and_contents__unified \"str1\" \"\${myvar}\"" -- -D myvar=trs2

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-21/probed_files/0_output_dir" -oempty -e "captured-data/k-21/stderr" run_replace_func template2 "prompt string myvar" "replace_in_file_names_and_contents__unified \"str1\" \"\${myvar}\" \"vis\"" -- -D myvar=trs2

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-22/probed_files/0_output_dir" -oempty -e "captured-data/k-22/stderr" -r 14 run_replace_func template2 "prompt string myvar" "replace_in_file_names_and_contents__unified \"str1\" \"\${myvar}\" \"vis\" \"non-exist\"" -- -D myvar=trs2

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-23/probed_files/0_output_dir" -oempty -e "captured-data/k-23/stderr" run_replace_func template2 "prompt string myvar" "replace_in_file_names_and_contents__unified \"str1\" \"\${myvar}\" \".\"" -- -D myvar=trs2

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-24/probed_files/0_output_dir" -oempty -e "captured-data/k-24/stderr" run_replace_func template2 "prompt string myvar" "replace_in_file_names_and_contents__unified \"str1\" \"\${myvar}\" \"vis\" \".str1\"" -- -D myvar=trs.2

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-25/probed_files/0_output_dir" -oempty -e "captured-data/k-25/stderr" run_replace_func template2 "prompt string myvar" "replace_in_file_names_and_contents__unified \"str1\" \"\${myvar}\" \".str1.py\" \"str1/.str1.sh\"" -- -D myvar=trs.2

stage_dir stage
expect_exec -f "output_dir" "captured-data/k-26/probed_files/0_output_dir" -oempty -e "captured-data/k-26/stderr" run_replace_func template2 "prompt string myvar" "replace_in_file_names_and_contents__unified \"str1.py\" \"\${myvar}\" \".\"" -- -D myvar=trs2.py


stage_dir stage
expect_exec -fu "output_dir" -f "templates_dir/template3/dir1" "captured-data/k-27/probed_files/1_templates_dir_dir1" -oempty -e "captured-data/k-27/stderr" -r 12 run_replace_func template3 "" "replace_in_file_names \"str\" \"rep\" \"dir1\""


stage_dir stage
expect_exec -fu "output_dir" -f "templates_dir/template3/dir1" "captured-data/k-28/probed_files/1_templates_dir_dir1" -oempty -e "captured-data/k-28/stderr" -r 12 run_replace_func template3 "" "replace_in_file_contents \"str\" \"rep\" \"dir1\""


stage_dir stage
expect_exec -fu "output_dir" -f "templates_dir/template3/dir1" "captured-data/k-29/probed_files/1_templates_dir_dir1" -oempty -e "captured-data/k-29/stderr" -r 12 run_replace_func template3 "" "replace_in_file_names_and_contents \"str\" \"rep\" \"dir1\""
