# Do not edit this file manually. It is automatically generated.
# Edit 'capture-all.sh' instead.


source ../../definitions.sh
source ../definitions.sh
source definitions.sh

_TT_check_stage_not_in_a_tps_repo


stage_dir stage
expect_exec -oempty -e "captured-data/k-0/stderr" -r 11 run_plain_prompt prompt

stage_dir stage
expect_exec -oempty -e "captured-data/k-1/stderr" -r 11 run_plain_prompt "prompt string"

stage_dir stage
expect_exec -oempty -e "captured-data/k-2/stderr" -r 11 run_plain_prompt "prompt string my_var a_description extra"


stage_dir stage
expect_exec -oempty -e "captured-data/k-3/stderr" -r 11 run_prompt an_invalid_type my_var

stage_dir stage
expect_exec -oempty -e "captured-data/k-4/stderr" -r 11 run_prompt an_invalid_type my_var "a description"

stage_dir stage
expect_exec -oempty -e "captured-data/k-5/stderr" -r 11 run_prompt string 1not_id


stage_dir stage
expect_exec -ih hi -oh2 "my_var=" "hi" -eh2 "Template parameter 'my_var'..." "Enter a value of type 'string' for 'my_var':" run_prompt string my_var

stage_dir stage
expect_exec -ih hi -oh2 "my_var=" "hi" -eh2 "Template parameter 'my_var' (a description)..." "Enter a value of type 'string' for 'my_var':" run_prompt string my_var "a description"

stage_dir stage
expect_exec -ih "hey you" -oh2 "my_var=" "hey you" -eh2 "Template parameter 'my_var'..." "Enter a value of type 'string' for 'my_var':" run_prompt string my_var

stage_dir stage
expect_exec -ih "" -oh2 "my_var=" "" -eh2 "Template parameter 'my_var'..." "Enter a value of type 'string' for 'my_var':" run_prompt string my_var

stage_dir stage
expect_exec -oh2 "my_var=" "hello" -eh2 "Template parameter 'my_var'..." "Parameter 'my_var' has predefined value 'hello'." run_prompt string my_var -- -D my_var=hello

stage_dir stage
expect_exec -oh2 "my_var=" "hello" -eh2 "Template parameter 'my_var' (a description)..." "Parameter 'my_var' has predefined value 'hello'." run_prompt string my_var "a description" -- --define my_var=hello


stage_dir stage
expect_exec -ih hi -oh2 "my_var=" "hi" -eh2 "Template parameter 'my_var'..." "Enter a value of type 'identifier' for 'my_var':" run_prompt identifier my_var

stage_dir stage
expect_exec -ih2 "hey you" hey_you -oh2 "my_var=" "hey_you" -e "captured-data/k-13/stderr" run_prompt identifier my_var

stage_dir stage
expect_exec -ih hi3 -oh2 "my_var=" "hi3" -eh2 "Template parameter 'my_var'..." "Enter a value of type 'identifier' for 'my_var':" run_prompt identifier my_var

stage_dir stage
expect_exec -ih2 3hi h3i -oh2 "my_var=" "h3i" -e "captured-data/k-15/stderr" run_prompt identifier my_var

stage_dir stage
expect_exec -ih2 "" t -oh2 "my_var=" "t" -e "captured-data/k-16/stderr" run_prompt identifier my_var

stage_dir stage
expect_exec -oh2 "my_var=" "aa" -eh2 "Template parameter 'my_var'..." "Parameter 'my_var' has predefined value 'aa'." run_prompt identifier my_var -- --define my_var=aa

stage_dir stage
expect_exec -ih hi -oh2 "my_var=" "hi" -e "captured-data/k-18/stderr" run_prompt identifier my_var -- -D my_var=1a


stage_dir stage
expect_exec -ih 0 -oh2 "my_var=" "0" -eh2 "Template parameter 'my_var'..." "Enter a value of type 'int' for 'my_var':" run_prompt int my_var

stage_dir stage
expect_exec -ih 1 -oh2 "my_var=" "1" -eh2 "Template parameter 'my_var'..." "Enter a value of type 'int' for 'my_var':" run_prompt int my_var

stage_dir stage
expect_exec -ih +1 -oh2 "my_var=" "+1" -eh2 "Template parameter 'my_var'..." "Enter a value of type 'int' for 'my_var':" run_prompt int my_var

stage_dir stage
expect_exec -ih -1 -oh2 "my_var=" "-1" -eh2 "Template parameter 'my_var'..." "Enter a value of type 'int' for 'my_var':" run_prompt int my_var

stage_dir stage
expect_exec -ih 0 -oh2 "my_var=" "0" -eh2 "Template parameter 'my_var'..." "Enter a value of type 'integer' for 'my_var':" run_prompt integer my_var

stage_dir stage
expect_exec -ih 30 -oh2 "my_var=" "30" -eh2 "Template parameter 'my_var'..." "Enter a value of type 'integer' for 'my_var':" run_prompt integer my_var

stage_dir stage
expect_exec -ih +30 -oh2 "my_var=" "+30" -eh2 "Template parameter 'my_var'..." "Enter a value of type 'integer' for 'my_var':" run_prompt integer my_var

stage_dir stage
expect_exec -ih -30 -oh2 "my_var=" "-30" -eh2 "Template parameter 'my_var'..." "Enter a value of type 'integer' for 'my_var':" run_prompt integer my_var

stage_dir stage
expect_exec -oh2 "my_var=" "40" -eh2 "Template parameter 'my_var'..." "Parameter 'my_var' has predefined value '40'." run_prompt integer my_var -- -D my_var=40

stage_dir stage
expect_exec -ih -30 -oh2 "my_var=" "-30" -e "captured-data/k-28/stderr" run_prompt int my_var -- -D my_var=x

stage_dir stage
expect_exec -ih 30 -oh2 "my_var=" "30" -e "captured-data/k-29/stderr" run_prompt integer my_var "a description" -- -D my_var=x

stage_dir stage
expect_exec -ih3 x 1.2 30 -oh2 "my_var=" "30" -e "captured-data/k-30/stderr" run_prompt int my_var

stage_dir stage
expect_exec -ih2 "" 30 -oh2 "my_var=" "30" -e "captured-data/k-31/stderr" run_prompt int my_var

stage_dir stage
expect_exec -ih2 x 30 -oh2 "my_var=" "30" -e "captured-data/k-32/stderr" run_prompt int my_var

stage_dir stage
expect_exec -ih2 1.2 30 -oh2 "my_var=" "30" -e "captured-data/k-33/stderr" run_prompt int my_var


stage_dir stage
expect_exec -ih 0 -oh2 "my_var=" "0" -eh2 "Template parameter 'my_var'..." "Enter a value of type 'uint' for 'my_var':" run_prompt uint my_var

stage_dir stage
expect_exec -ih 1 -oh2 "my_var=" "1" -eh2 "Template parameter 'my_var'..." "Enter a value of type 'uint' for 'my_var':" run_prompt uint my_var

stage_dir stage
expect_exec -ih 0 -oh2 "my_var=" "0" -eh2 "Template parameter 'my_var'..." "Enter a value of type 'unsigned_integer' for 'my_var':" run_prompt unsigned_integer my_var

stage_dir stage
expect_exec -ih 30 -oh2 "my_var=" "30" -eh2 "Template parameter 'my_var'..." "Enter a value of type 'unsigned_integer' for 'my_var':" run_prompt unsigned_integer my_var

stage_dir stage
expect_exec -ih2 +30 20 -oh2 "my_var=" "20" -e "captured-data/k-38/stderr" run_prompt unsigned_integer my_var

stage_dir stage
expect_exec -ih2 -30 20 -oh2 "my_var=" "20" -e "captured-data/k-39/stderr" run_prompt unsigned_integer my_var

stage_dir stage
expect_exec -oh2 "my_var=" "40" -eh2 "Template parameter 'my_var'..." "Parameter 'my_var' has predefined value '40'." run_prompt unsigned_integer my_var -- -D my_var=40

stage_dir stage
expect_exec -ih 30 -oh2 "my_var=" "30" -e "captured-data/k-41/stderr" run_prompt uint my_var -- -D my_var=x

stage_dir stage
expect_exec -ih 30 -oh2 "my_var=" "30" -e "captured-data/k-42/stderr" run_prompt unsigned_integer my_var "a description" -- -D my_var=-2

stage_dir stage
expect_exec -ih3 -1 1.2 30 -oh2 "my_var=" "30" -e "captured-data/k-43/stderr" run_prompt uint my_var

stage_dir stage
expect_exec -ih2 "" 30 -oh2 "my_var=" "30" -e "captured-data/k-44/stderr" run_prompt uint my_var

stage_dir stage
expect_exec -ih2 -1 30 -oh2 "my_var=" "30" -e "captured-data/k-45/stderr" run_prompt uint my_var

stage_dir stage
expect_exec -ih2 +1 30 -oh2 "my_var=" "30" -e "captured-data/k-46/stderr" run_prompt uint my_var

stage_dir stage
expect_exec -ih2 x 30 -oh2 "my_var=" "30" -e "captured-data/k-47/stderr" run_prompt uint my_var

stage_dir stage
expect_exec -ih2 1.2 30 -oh2 "my_var=" "30" -e "captured-data/k-48/stderr" run_prompt uint my_var


stage_dir stage
expect_exec -ih 0 -oh2 "my_var=" "0" -eh2 "Template parameter 'my_var'..." "Enter a value of type 'decimal' for 'my_var':" run_prompt decimal my_var

stage_dir stage
expect_exec -ih 1 -oh2 "my_var=" "1" -eh2 "Template parameter 'my_var'..." "Enter a value of type 'decimal' for 'my_var':" run_prompt decimal my_var

stage_dir stage
expect_exec -ih 1.2 -oh2 "my_var=" "1.2" -eh2 "Template parameter 'my_var'..." "Enter a value of type 'decimal' for 'my_var':" run_prompt decimal my_var

stage_dir stage
expect_exec -ih +1 -oh2 "my_var=" "+1" -eh2 "Template parameter 'my_var'..." "Enter a value of type 'decimal' for 'my_var':" run_prompt decimal my_var

stage_dir stage
expect_exec -ih -1 -oh2 "my_var=" "-1" -eh2 "Template parameter 'my_var'..." "Enter a value of type 'decimal' for 'my_var':" run_prompt decimal my_var

stage_dir stage
expect_exec -ih -1.2 -oh2 "my_var=" "-1.2" -eh2 "Template parameter 'my_var'..." "Enter a value of type 'decimal' for 'my_var':" run_prompt decimal my_var

stage_dir stage
expect_exec -ih +1.2 -oh2 "my_var=" "+1.2" -eh2 "Template parameter 'my_var'..." "Enter a value of type 'decimal' for 'my_var':" run_prompt decimal my_var

stage_dir stage
expect_exec -oh2 "my_var=" "4.3" -eh2 "Template parameter 'my_var'..." "Parameter 'my_var' has predefined value '4.3'." run_prompt decimal my_var -- -D my_var=4.3

stage_dir stage
expect_exec -ih -30 -oh2 "my_var=" "-30" -e "captured-data/k-57/stderr" run_prompt decimal my_var -- -D my_var=x

stage_dir stage
expect_exec -ih 3.0 -oh2 "my_var=" "3.0" -e "captured-data/k-58/stderr" run_prompt decimal my_var "a description" -- -D my_var=x

stage_dir stage
expect_exec -ih3 x y 3.1 -oh2 "my_var=" "3.1" -e "captured-data/k-59/stderr" run_prompt decimal my_var

stage_dir stage
expect_exec -ih2 "" 3.5 -oh2 "my_var=" "3.5" -e "captured-data/k-60/stderr" run_prompt decimal my_var

stage_dir stage
expect_exec -ih2 x 3.5 -oh2 "my_var=" "3.5" -e "captured-data/k-61/stderr" run_prompt decimal my_var


stage_dir stage
expect_exec -ih 0 -oh2 "my_var=" "0" -eh2 "Template parameter 'my_var'..." "Enter a value of type 'udecimal' for 'my_var':" run_prompt udecimal my_var

stage_dir stage
expect_exec -ih 1 -oh2 "my_var=" "1" -eh2 "Template parameter 'my_var'..." "Enter a value of type 'udecimal' for 'my_var':" run_prompt udecimal my_var

stage_dir stage
expect_exec -ih 1.2 -oh2 "my_var=" "1.2" -eh2 "Template parameter 'my_var'..." "Enter a value of type 'udecimal' for 'my_var':" run_prompt udecimal my_var

stage_dir stage
expect_exec -ih 0 -oh2 "my_var=" "0" -eh2 "Template parameter 'my_var'..." "Enter a value of type 'unsigned_decimal' for 'my_var':" run_prompt unsigned_decimal my_var

stage_dir stage
expect_exec -ih 1 -oh2 "my_var=" "1" -eh2 "Template parameter 'my_var'..." "Enter a value of type 'unsigned_decimal' for 'my_var':" run_prompt unsigned_decimal my_var

stage_dir stage
expect_exec -ih 1.2 -oh2 "my_var=" "1.2" -eh2 "Template parameter 'my_var'..." "Enter a value of type 'unsigned_decimal' for 'my_var':" run_prompt unsigned_decimal my_var

stage_dir stage
expect_exec -ih2 +1 0.5 -oh2 "my_var=" "0.5" -e "captured-data/k-68/stderr" run_prompt unsigned_decimal my_var

stage_dir stage
expect_exec -ih2 -1 0.5 -oh2 "my_var=" "0.5" -e "captured-data/k-69/stderr" run_prompt unsigned_decimal my_var

stage_dir stage
expect_exec -ih2 -1.2 0.5 -oh2 "my_var=" "0.5" -e "captured-data/k-70/stderr" run_prompt unsigned_decimal my_var

stage_dir stage
expect_exec -ih2 +1.2 0.5 -oh2 "my_var=" "0.5" -e "captured-data/k-71/stderr" run_prompt unsigned_decimal my_var

stage_dir stage
expect_exec -oh2 "my_var=" "4.3" -eh2 "Template parameter 'my_var'..." "Parameter 'my_var' has predefined value '4.3'." run_prompt udecimal my_var -- -D my_var=4.3

stage_dir stage
expect_exec -ih 30 -oh2 "my_var=" "30" -e "captured-data/k-73/stderr" run_prompt unsigned_decimal my_var -- -D my_var=x

stage_dir stage
expect_exec -ih 3.0 -oh2 "my_var=" "3.0" -e "captured-data/k-74/stderr" run_prompt unsigned_decimal my_var "a description" -- -D my_var=x

stage_dir stage
expect_exec -ih3 x y 3.1 -oh2 "my_var=" "3.1" -e "captured-data/k-75/stderr" run_prompt udecimal my_var

stage_dir stage
expect_exec -ih2 "" 3.5 -oh2 "my_var=" "3.5" -e "captured-data/k-76/stderr" run_prompt udecimal my_var

stage_dir stage
expect_exec -ih2 +1 3.5 -oh2 "my_var=" "3.5" -e "captured-data/k-77/stderr" run_prompt udecimal my_var

stage_dir stage
expect_exec -ih2 -1 3.5 -oh2 "my_var=" "3.5" -e "captured-data/k-78/stderr" run_prompt udecimal my_var

stage_dir stage
expect_exec -ih2 +1.2 3.5 -oh2 "my_var=" "3.5" -e "captured-data/k-79/stderr" run_prompt udecimal my_var

stage_dir stage
expect_exec -ih2 -1.2 3.5 -oh2 "my_var=" "3.5" -e "captured-data/k-80/stderr" run_prompt udecimal my_var

stage_dir stage
expect_exec -ih2 x 3.5 -oh2 "my_var=" "3.5" -e "captured-data/k-81/stderr" run_prompt udecimal my_var


stage_dir stage
expect_exec -ih true -oh2 "my_var=" "true" -eh2 "Template parameter 'my_var'..." "Enter a value of type 'bool' for 'my_var':" run_prompt bool my_var

stage_dir stage
expect_exec -ih true -oh2 "my_var=" "true" -eh2 "Template parameter 'my_var'..." "Parameter 'my_var' has predefined value 'true'." run_prompt bool my_var -- -D my_var=true

stage_dir stage
expect_exec -ih yes -oh2 "my_var=" "true" -eh2 "Template parameter 'my_var'..." "Enter a value of type 'bool' for 'my_var':" run_prompt bool my_var

stage_dir stage
expect_exec -ih yes -oh2 "my_var=" "true" -eh2 "Template parameter 'my_var'..." "Parameter 'my_var' has predefined value 'yes'." run_prompt bool my_var -- -D my_var=yes

stage_dir stage
expect_exec -ih y -oh2 "my_var=" "true" -eh2 "Template parameter 'my_var'..." "Enter a value of type 'bool' for 'my_var':" run_prompt bool my_var

stage_dir stage
expect_exec -ih y -oh2 "my_var=" "true" -eh2 "Template parameter 'my_var'..." "Parameter 'my_var' has predefined value 'y'." run_prompt bool my_var -- -D my_var=y

stage_dir stage
expect_exec -ih false -oh2 "my_var=" "false" -eh2 "Template parameter 'my_var'..." "Enter a value of type 'bool' for 'my_var':" run_prompt bool my_var

stage_dir stage
expect_exec -ih false -oh2 "my_var=" "false" -eh2 "Template parameter 'my_var'..." "Parameter 'my_var' has predefined value 'false'." run_prompt bool my_var -- -D my_var=false

stage_dir stage
expect_exec -ih no -oh2 "my_var=" "false" -eh2 "Template parameter 'my_var'..." "Enter a value of type 'bool' for 'my_var':" run_prompt bool my_var

stage_dir stage
expect_exec -ih no -oh2 "my_var=" "false" -eh2 "Template parameter 'my_var'..." "Parameter 'my_var' has predefined value 'no'." run_prompt bool my_var -- -D my_var=no

stage_dir stage
expect_exec -ih n -oh2 "my_var=" "false" -eh2 "Template parameter 'my_var'..." "Enter a value of type 'bool' for 'my_var':" run_prompt bool my_var

stage_dir stage
expect_exec -ih n -oh2 "my_var=" "false" -eh2 "Template parameter 'my_var'..." "Parameter 'my_var' has predefined value 'n'." run_prompt bool my_var -- -D my_var=n

stage_dir stage
expect_exec -ih2 "" yes -oh2 "my_var=" "true" -e "captured-data/k-94/stderr" run_prompt bool my_var

stage_dir stage
expect_exec -ih2 q yes -oh2 "my_var=" "true" -e "captured-data/k-95/stderr" run_prompt bool my_var

stage_dir stage
expect_exec -ih2 1 yes -oh2 "my_var=" "true" -e "captured-data/k-96/stderr" run_prompt bool my_var

stage_dir stage
expect_exec -ih2 0 yes -oh2 "my_var=" "true" -e "captured-data/k-97/stderr" run_prompt bool my_var

stage_dir stage
expect_exec -ih 0 -oempty -e "captured-data/k-98/stderr" -r 11 run_prompt enum my_var

stage_dir stage
expect_exec -ih 0 -oempty -e "captured-data/k-99/stderr" -r 11 run_prompt enum: my_var

stage_dir stage
expect_exec -ih 0 -oempty -e "captured-data/k-100/stderr" -r 11 run_prompt enum:1dog my_var

stage_dir stage
expect_exec -ih 0 -oempty -e "captured-data/k-101/stderr" -r 11 run_prompt enum:cat:1dog my_var

stage_dir stage
expect_exec -ih dog -oh2 "my_var=" "dog" -eh2 "Template parameter 'my_var'..." "Enter a value among {dog} for 'my_var':" run_prompt enum:dog my_var

stage_dir stage
expect_exec -ih cat -oh2 "my_var=" "cat" -eh2 "Template parameter 'my_var'..." "Enter a value among {cat, dog} for 'my_var':" run_prompt enum:cat:dog my_var

stage_dir stage
expect_exec -ih dog -oh2 "my_var=" "dog" -eh2 "Template parameter 'my_var'..." "Enter a value among {cat, dog} for 'my_var':" run_prompt enum:cat:dog my_var

stage_dir stage
expect_exec -ih cat -oh2 "my_var=" "cat" -eh2 "Template parameter 'my_var'..." "Enter a value among {cat, dog, hen} for 'my_var':" run_prompt enum:cat:dog:hen my_var

stage_dir stage
expect_exec -ih dog -oh2 "my_var=" "dog" -eh2 "Template parameter 'my_var'..." "Enter a value among {cat, dog, hen} for 'my_var':" run_prompt enum:cat:dog:hen my_var

stage_dir stage
expect_exec -ih hen -oh2 "my_var=" "hen" -eh2 "Template parameter 'my_var'..." "Enter a value among {cat, dog, hen} for 'my_var':" run_prompt enum:cat:dog:hen my_var

stage_dir stage
expect_exec -ih2 x dog -oh2 "my_var=" "dog" -e "captured-data/k-108/stderr" run_prompt enum:cat:dog:hen my_var
