# Do not edit this file manually. It is automatically generated.
# Edit 'capture-all.sh' instead.

source ../definition_source_util_sh.sh

stage_an_empty_dir

expect_exec -oh "" -eempty extension ""
expect_exec -oh "txt" -eempty extension a.txt
expect_exec -oh "txt" -eempty extension .a.txt
expect_exec -oh "" -eempty extension a.
expect_exec -oh "" -eempty extension .a.
expect_exec -oh "c" -eempty extension a.b.c
expect_exec -oh "txt" -eempty extension a/b.txt
expect_exec -oh "txt" -eempty extension a/b/c.txt
expect_exec -oh "txt" -eempty extension a/b.c.txt
