# Do not edit this file manually. It is automatically generated.
# Edit 'capture-all.sh' instead.

source ../definition_source_util_sh.sh
source definitions.sh

stage_an_empty_dir

expect_exec -oempty -eempty variable_exists a_variable_that_should_exist
expect_exec -oempty -eempty variable_exists an_empty_variable_that_should_exist
expect_exec -oempty -eempty -r 1 variable_exists a_variable_that_should_not_exist
expect_exec -oempty -eempty -r 1 variable_exists a_variable_that_is_unset
expect_exec -oempty -eempty variable_exists array0
expect_exec -oempty -eempty variable_exists array1
expect_exec -oempty -eempty variable_exists array2
expect_exec -oempty -eempty variable_exists array3

expect_exec -oempty -eempty -r 1 variable_not_exists a_variable_that_should_exist
expect_exec -oempty -eempty -r 1 variable_not_exists an_empty_variable_that_should_exist
expect_exec -oempty -eempty variable_not_exists a_variable_that_should_not_exist
expect_exec -oempty -eempty variable_not_exists a_variable_that_is_unset
expect_exec -oempty -eempty -r 1 variable_not_exists array0
expect_exec -oempty -eempty -r 1 variable_not_exists array1
expect_exec -oempty -eempty -r 1 variable_not_exists array2
expect_exec -oempty -eempty -r 1 variable_not_exists array3

expect_exec -oempty -eempty check_variable a_variable_that_should_exist
expect_exec -oempty -eempty check_variable an_empty_variable_that_should_exist
expect_exec -oempty -eh "Error: Variable 'a_variable_that_should_not_exist' is not set." -r 1 check_variable a_variable_that_should_not_exist
expect_exec -oempty -eh "Error: Variable 'a_variable_that_is_unset' is not set." -r 1 check_variable a_variable_that_is_unset
expect_exec -oempty -eempty check_variable array0
expect_exec -oempty -eempty check_variable array1
expect_exec -oempty -eempty check_variable array2
expect_exec -oempty -eempty check_variable array3

unset my_new_var
expect_exec -vu my_new_var -oempty -eempty true
expect_exec -vs my_new_var "my-new-value" -oempty -eempty set_variable my_new_var my-new-value
expect_exec -vs my_new_var "my new value" -oempty -eempty set_variable my_new_var "my new value"
expect_exec -vf my_new_var "captured-data/k-27/probed_variables/0_my_new_var" -oempty -eempty set_variable my_new_var "my
new value"

export my_counter=20

expect_exec -vs my_counter "21" -oempty -eempty increment my_counter
expect_exec -vs my_counter "21" -oempty -eempty increment my_counter 1
expect_exec -vs my_counter "22" -oempty -eempty increment my_counter 2
expect_exec -vs my_counter "30" -oempty -eempty increment my_counter 10

expect_exec -vs my_counter "19" -oempty -eempty decrement my_counter
expect_exec -vs my_counter "19" -oempty -eempty decrement my_counter 1
expect_exec -vs my_counter "18" -oempty -eempty decrement my_counter 2
expect_exec -vs my_counter "10" -oempty -eempty decrement my_counter 10
