# Do not edit this file manually. It is automatically generated.
# Edit 'capture-all.sh' instead.

source ../definition_source_util_sh.sh

stage_an_empty_dir

expect_exec -oempty -eh "" errcho
expect_exec -oempty -eh "aha" errcho aha
expect_exec -oempty -eh "aha ehe" errcho aha ehe
expect_exec -oempty -eh "aha ehe" errcho "aha ehe"
expect_exec -oempty -eh "aha ehe oho" errcho aha ehe oho
expect_exec -oempty -eh "aha ehe oho" errcho aha "ehe oho"
expect_exec -oempty -eempty errcho -n
expect_exec -oempty -eH "aha" errcho -n aha
expect_exec -oempty -eH "aha ehe" errcho -n aha ehe
expect_exec -oempty -eH "aha ehe" errcho -n "aha ehe"
expect_exec -oempty -eH "aha ehe oho" errcho -n aha ehe oho
expect_exec -oempty -eH "aha ehe oho" errcho -n aha "ehe oho"
expect_exec -oempty -eh "aha\\tehe" errcho "aha\\tehe"
expect_exec -oempty -eh "aha	ehe" errcho -e "aha\\tehe"

expect_exec -oempty -eempty hspace 0
expect_exec -oH " " -eempty hspace 1
expect_exec -oH "  " -eempty hspace 2
expect_exec -oH "   " -eempty hspace 3
expect_exec -oH "          " -eempty hspace 10
