# Do not edit this file manually. It is automatically generated.
# Edit 'capture-all.sh' instead.

source ../../definition_get_head.sh
source ../../definition_not_web_terminal.sh
source definitions.sh


stage_dir_with_scripts stage-without-grader


expect_exec -oempty -e "captured-data/k-0/stderr" tcompile --help

expect_exec -oempty -e "captured-data/k-1/stderr" -rnz tcompile

expect_exec -oempty -e "captured-data/k-2/stderr" -rnz tcompile solution/correct1.cpp another-arg

expect_exec -oempty -e "captured-data/k-3/stderr" -rnz tcompile solution/correct1.cpp --unknown-flag

expect_exec -oempty -e "captured-data/k-4/stderr" -rnz tcompile -p solution/correct1.cpp

expect_exec -oh "OK" -eempty tcompile solution/correct1.cpp

expect_exec -oh "OK" -eempty tcompile -w solution/correct1.cpp
expect_exec -ih "2 3" -oh "5" -eempty trun

expect_exec -oh "OK" -eempty tcompile solution/wrong1.cpp
expect_exec -ih "2 3" -oh "6" -eempty trun

run_in_stage rm -rf sandbox

expect_exec -oh "OK" -eempty tcompile solution/correct-args1.cpp
expect_exec -ih "2 3" -oh2 "#args=0" "5" -eempty trun
expect_exec -ih "2 3" -oh3 "#args=1" "arg[1]='a'" "5" -eempty trun a
expect_exec -ih "2 3" -oh4 "#args=2" "arg[1]='a'" "arg[2]='b'" "5" -eempty trun a b

expect_exec -oh "OK" -eempty tcompile solution/rte1.cpp
expect_exec -ih "2 3" -oempty -eempty -rnz trun

expect_exec -oh "OK, but with warnings" -eempty get_head -1 0 tcompile solution/correct1-warn.cpp
expect_exec -ih "2 3" -oh "5" -eempty trun

expect_exec -oh "FAILED, due to sensitivity to warnings" -eempty -rnz get_head -1 0 tcompile -w solution/correct1-warn.cpp

expect_exec -oh "FAILED." -eempty -rnz get_head -1 0 tcompile solution/compile_error1.cpp

expect_exec -oh "FAILED." -eempty -rnz get_head -1 0 tcompile -w solution/compile_error1.cpp

run_in_stage rm -rf sandbox

expect_exec -oh "OK" -eempty get_head -1 0 tcompile solution/correct1.py

expect_exec -oh "OK" -eempty get_head -1 0 tcompile -w solution/correct1.py
expect_exec -ih "2 3" -oh "5" -eempty trun

expect_exec -oh "OK" -eempty get_head -1 0 tcompile solution/wrong1.py
expect_exec -ih "2 3" -oh "6" -eempty trun

run_in_stage rm -rf sandbox

expect_exec -oh "OK" -eempty get_head -1 0 tcompile solution/correct-args1.py
expect_exec -ih "2 3" -oh2 "#args=0" "5" -eempty trun
expect_exec -ih "2 3" -oh3 "#args=1" "arg[1]='a'" "5" -eempty trun a
expect_exec -ih "2 3" -oh4 "#args=2" "arg[1]='a'" "arg[2]='b'" "5" -eempty trun a b

expect_exec -oh "OK" -eempty get_head -1 0 tcompile solution/rte1.py
expect_exec -ih "2 3" -oempty -eempty -rnz trun


stage_dir_with_scripts stage-with-grader


expect_exec -oh "OK" -eempty tcompile solution/correct1.cpp

expect_exec -oh "OK" -eempty tcompile -w solution/correct1.cpp
expect_exec -ih "2 3" -oh2 "OK" "5" -eempty trun

expect_exec -oh "OK" -eempty tcompile -p solution/correct1.cpp

expect_exec -oh "OK" -eempty tcompile -pw solution/correct1.cpp
expect_exec -ih "2 3" -oh "5" -eempty trun

run_in_stage rm -rf sandbox

expect_exec -oh "OK" -eempty get_head -1 0 tcompile solution/correct1.py

expect_exec -oh "OK" -eempty get_head -1 0 tcompile -w solution/correct1.py
expect_exec -ih "2 3" -oh2 "OK" "5" -eempty trun

expect_exec -oh "OK" -eempty get_head -1 0 tcompile -p solution/correct1.py

expect_exec -oh "OK" -eempty get_head -1 0 tcompile -pw solution/correct1.py
expect_exec -ih "2 3" -oh "5" -eempty trun
