# Do not edit this file manually. It is automatically generated.
# Edit 'capture-all.sh' instead.

stage_dir "stage"

expect_exec -oh5 "TPS version 1.1" "" "Usage: tps <command> <arguments>..." "" "Directory 'scripts' is not available." -eempty -r 1 tps
expect_exec -oempty -eh "Error: Directory 'scripts' not found." -r 2 tps a_command
expect_exec -oempty -eh "Error: Directory 'scripts' not found." -r 2 tps a_command a_param

expect_exec -oempty -eempty tps_bc 1 0
expect_exec -oempty -eempty tps_bc 1 0 a_command
expect_exec -oempty -eempty tps_bc 1 1 a_command
expect_exec -oempty -eempty tps_bc 1 0 a_command a_param
expect_exec -oempty -eempty tps_bc 1 1 a_command a_param
